-- Sync cast data from local DB to production
-- This migration sets cast for every show to match the local DB state.
-- Generated on 2026-03-01T11:32:11.424Z
-- Shows with cast: 69, Shows with NULL cast: 185

UPDATE "Show" SET "cast" = 'דן שפירא, אבי בנימין' WHERE "slug" = 'AI-וחדשנות-ספרותית-–-דוד-אבידן-ועוד';
UPDATE "Show" SET "cast" = 'ריקי בליך, אסנת פישמן, יעל לבנטל, שירן הוברמן / רוני מרחבי, רינת מטטוב' WHERE "slug" = 'מי-את-חושבת-שאת';
UPDATE "Show" SET "cast" = 'נדב אסולין, אביגיל הררי / מיכל עוזיאל, ענת וקסמן, יואב לוי, כינרת לימוני / מורן ארביב גנס, מיכה סלקטר, ליר עיסא, ליעם פינטו' WHERE "slug" = 'מי-בעד';
UPDATE "Show" SET "cast" = 'אודיה קורן, מוטי כץ / רמי ברוך, ישי גולן, אנדריאה שוורץ, נטע שפיגלמן / מורן ארביב גנס, שירן בוחניק / גל סרי' WHERE "slug" = 'מה-קרה-לעולם';
UPDATE "Show" SET "cast" = 'בן איזדי, ערן בראש' WHERE "slug" = 'מה-שנשאר-לך-בברלין';
UPDATE "Show" SET "cast" = 'רמי ברוך, סנדרה שדה, נעמה שטרית, אוריה יבלונובסקי, אנדריאה שוורץ, דויד בילנקה / גלעד שמואלי, רפאל עבאס / אלון סנדלר, סנדרה שונוולד, יונתן ורמן, ליאם טליו' WHERE "slug" = 'לא-הייתם-צריכים';
UPDATE "Show" SET "cast" = 'רודיה קוזלובסקי, רוני שטקלר, ליאור אביבי, שירי לוטן' WHERE "slug" = 'זו-שכותבת-אותי';
UPDATE "Show" SET "cast" = 'דביר בנדק' WHERE "slug" = 'כל-הדברים-הטובים';
UPDATE "Show" SET "cast" = 'רמי ברוך / ערן מור, נדב נייטס / גלעד שמואלי, אלון סנדלר / דוד בילנקה, אלי גורנשטיין / שמחה ברבירו, ירדן ניקפהמה / נוי הלפרין / נעמה שטרית, איה שבא / נעמה שטרית, עירית קפלן / כנרת לימוני / איה גרניט שבא, שהם שיינר / דודו ניב, טל וייס / עופרי ביטרמן, אדיר בובליל, מתן בן שימול' WHERE "slug" = 'עוץ-לי-גוץ-לי';
UPDATE "Show" SET "cast" = 'ענת ברזילי, אסנת פישמן, אסתי זקהיים, גיא מרוז, טס השילוני, מיה לנדסמן, נתי קלוגר, מייקל גרינשפן, שלמה משיח, מיכאל יוחאי' WHERE "slug" = 'גרה-עם-קושמרו';
UPDATE "Show" SET "cast" = 'עמוס תמם, מתי סרי, ריטה שוקרון, מורן ארביב גנס / שני שאולי, טל וייס, אנסטסיה פיין, שמחה ברבירו' WHERE "slug" = 'הבן-של-מושיקו-הגדול';
UPDATE "Show" SET "cast" = 'בן אדם, גאיה ענבר' WHERE "slug" = 'אחד-בלי-השני';
UPDATE "Show" SET "cast" = 'דרור קרן, איה גרניט שבא, יגאל זקס, ניר ברק' WHERE "slug" = 'סוס-אחד-נכנס-לבר';
UPDATE "Show" SET "cast" = 'דביר בנדק, דן שפירא, ירדן ניקפהמה / מיכל עוזיאל, הלנה ירלובה, אבי טרמין, נעם ברט, אור שמריהו / יונתן דהאן / אורי זיו גדניר.' WHERE "slug" = 'איש-הגשם';
UPDATE "Show" SET "cast" = 'אלון סנדלר / רפאל עבאס, טלי אורן, דיאנה גולבי / נוי הלפרין, אולה שור סלקטר, יניב סויסה, אלעד אטרקצ''י / אדיר שטיבלמן, עמית שושני, מירי זהבי, בר כהן / אריאל מגידש, דביר עונה, טל בן אהרון' WHERE "slug" = 'היי-אוון-הנסן';
UPDATE "Show" SET "cast" = 'שני כהן, יגאל שדה, ריקי בליך, יהויכין פרידלנדר, עודד לאופולד, וונינה פנרס, רועי אפלבאום / יואב ברק, איה זמיר / רוני אורגד, טל ליבוביץ׳, יובל קלע / ירין טייר' WHERE "slug" = 'בית-בובות';
UPDATE "Show" SET "cast" = 'לוטם רייכנטל, סתיו רייכנטל, ליאור ברגר, מאיה משעול' WHERE "slug" = 'הדב-השומר-עליי';
UPDATE "Show" SET "cast" = 'יעל לבנטל / ריקי בליך, נורמן עיסא, יואב רוזנברג' WHERE "slug" = 'אוי-אלוהים';
UPDATE "Show" SET "cast" = 'דביר בנדק, תמר דיסקין, גיא כהן שלו, אדוה לוי, דר רוזנבאום, עומר שמשוני' WHERE "slug" = 'האבא';
UPDATE "Show" SET "cast" = 'רן דנקר, חני פירסטנברג / ליהי טולדנו, נדב נייטס, לאורה ריבלין, עמי ויינברג, כינרת לימוני, שהם שיינר, מתן און ימי, טל פרלמן / רום צרניאק / נתנאל אוליבקוביץ / סער-רז פלינקר' WHERE "slug" = 'קברט';
UPDATE "Show" SET "cast" = 'אברהם ארנסון, נעמי הררי, דוית גביש, מיקי פלג רוטשטיין, יגאל שדה' WHERE "slug" = 'רומי-+-ג׳ולייט';
UPDATE "Show" SET "cast" = 'אלון סנדלר, מיה לנדסמן / יעלי רוזנבליט, עופרי ביטרמן / תום חודורוב, אלעד אטרקצ''י / ערן מור, נעם ברט, נדב נייטס / גלעד מרחבי / עמית שושני, ערן מור / גיא רוזן, שון מונגוזה / מתן און ימי, ליעם פינטו / גיא רוזן' WHERE "slug" = 'פיטר-פן';
UPDATE "Show" SET "cast" = 'ליא קניג, מאיה מעוז, נעמי הררי' WHERE "slug" = 'משהו-טוב';
UPDATE "Show" SET "cast" = 'אודיה קורן, נטע גרטי' WHERE "slug" = 'לילה-טוב-אמא';
UPDATE "Show" SET "cast" = 'לידור אדמוני, דולב אוחנה, תם גל, תום חודורוב, אוריה יבלונובסקי, רוני נתנאל, מאיה קורן, יעלי רוזנבליט / כרמל נצר, יצחק חזקיה' WHERE "slug" = 'מיקי-מציל';
UPDATE "Show" SET "cast" = 'יעל לבנטל, גיא אריאלי, דוית גביש, אורי הוכמן / עמי סמולרצ׳יק' WHERE "slug" = 'מעבר-לדלת';
UPDATE "Show" SET "cast" = 'ג׳וי ריגר, נורמן עיסא, תומר מחלוף, מאיה מעוז, ליאור זוהר, ישי בן משה, אלכס קרול, אושרת אינגדשט, אילי עלמני, מיכל אטלס, עודד לאופולד, שחר רז, מאיה מדג׳ר, ניר זליחובסקי, איתי טרנרודר, עמית גלבע / ג׳ימי מנדיל' WHERE "slug" = 'מעגל-הגיר-הקווקזי';
UPDATE "Show" SET "cast" = 'אביגיל הררי, תום אבני, אלעד אטרקצ''י, דורית לב ארי, הלנה ירלובה, שהם שיינר, רפאל עבאס, נדב עדר, ירדן ניקפהמה / גל סרי' WHERE "slug" = 'הנפש-הטובה-מסצ׳ואן';
UPDATE "Show" SET "cast" = 'יעל עוזר, הדר שיש' WHERE "slug" = 'בחור-לחתונה';
UPDATE "Show" SET "cast" = 'אריה צ׳רנר, גילת אנקורי / ליאת גורן, צחי הלוי / יפתח קליין, ריקי בליך / מלי לוי, יגאל נאור, ניר זליחובסקי, רונית אפל / ספיר אזולאי, סתיו וקנין / נעמי הררי, שפי מרציאנו / חנן שוורצברג, ניל משען / חנן שוורצברג, מיכל ברנד, מאיה מדג׳ר / ספיר אזולאי, עמוס בוארון, נועם בירגר / רועי אפלבאום / יואב ברק' WHERE "slug" = 'הערת-שוליים';
UPDATE "Show" SET "cast" = 'רבקה מיכאלי, עירית קפלן, נדב אסולין / ישי גולן, שהם שיינר / טל וייס, אסנת בן יהודה, דולב אוחנה / אלעד שנקר' WHERE "slug" = 'נעמי-ונורמה';
UPDATE "Show" SET "cast" = 'ישי גולן, גיא רון, גילי בית הלחמי, הראל מוראד, אייל רדושיצקי' WHERE "slug" = 'התקלה';
UPDATE "Show" SET "cast" = 'עמוס תמם, נדב נייטס, רוי מילר, רמי ברוך, אלינור וייל, אבי טרמין, אסתי קוסוביצקי / הלנה ירלובה, מתן און ימי, טובית סמאי, עמית שושני, נעם ברט, גלי פרנק, טל פרלמן, אריאל קורט' WHERE "slug" = 'זינגר';
UPDATE "Show" SET "cast" = 'דרור קרן, אולה שור סלקטר / אנסטסיה פיין, נדב נייטס, אלעד אטרקצ''י, איה גרניט שבא, דויד בילנקה / דן שפירא, גלעד שמואלי / עופרי ביטרמן, חן גרטי / רוני נתנאל, גלעד מרחבי' WHERE "slug" = 'טרטיף';
UPDATE "Show" SET "cast" = 'כינרת לימוני, עמוס תמם, אנסטסיה פיין, מוטי כץ, רות אסרסאי, טל פרלמן, אביב לוי / אורי אגת / עומרי יוגב' WHERE "slug" = 'מדיאה';
UPDATE "Show" SET "cast" = 'איתי לוי / עופר חיון, פיני קדרון, שירן הוברמן / עדי כהן, שמוליק כהן / עודד לאופולד / מיכאל כורש, עדי זורע, עמית פרקש / אילי עלמני / מאי מלר, טל קלאי, עודד מנסטר, טל מוסרי, דניאל חסין / אבירם קליך, שחר רז, טירל יגוני, ניל משען / לירן מזרחי, אלינור פלקסמן, הילה הויזמן / מאיה מדג׳ר, שפי מרציאנו, עמית רייס / חנן שוורצברג, זיו עוז ארי / מאור לוי, לירון כהן / אורי לביא, רותם יהודה / עדן אמסילי' WHERE "slug" = 'קזבלן';
UPDATE "Show" SET "cast" = 'אלעד אטרקצ''י / רועי רביב, תם גל, חן גרטי / נעמה שטרית, בן פרי, תום חודורוב, אוריה יבלונובסקי, גל סרי / עמית פרטוק, רוני נתנאל, מאיה קורן, יעלי רוזנבליט / כרמל נצר' WHERE "slug" = 'רינגו';
UPDATE "Show" SET "cast" = 'יניב סויסה / מוטי כץ, אודיה קורן / מורן ארביב גנס, גלעד שמואלי / תום חודורוב, נעמה שטרית / חן גרטי / נוי הלפרין, עופרי ביטרמן / אלון סנדלר' WHERE "slug" = 'מישהו-שר-את-זה-קודם';
UPDATE "Show" SET "cast" = 'עירית קפלן, איציק כהן, אלעד אטרקצ''י / עופרי ביטרמן, דודו ניב, אסנת בן יהודה, שמחה ברבירו, טל וייס' WHERE "slug" = 'לנקות-את-הראש';
UPDATE "Show" SET "cast" = 'צביקה הדר, חן אמסלם / הגר טישמן, עמי סמולרצ׳יק / טל קלאי, אושרת אינגדשט, דב רייזר / יהויכין פרידלנדר, רובי פורת שובל, שחר רז, עדנה בליליוס / דוית גביש, אלינור פלקסמן, שמוליק כהן, דורין פלטיאל, ליהי גל, לאה אלון מגן' WHERE "slug" = 'תרקדי-איתי';
UPDATE "Show" SET "cast" = 'נורית בוכובזה חרר, אושר דניאל, שני הדר, כפיר הוד, בר חיניץ, שלי ישי, חנה תבור, דור טרייסטמן, נועם רבי בראל, אסף סער' WHERE "slug" = 'אזהרת-טריגר';
UPDATE "Show" SET "cast" = 'כרמל זורע, שון אמסלם' WHERE "slug" = 'באמצע-הרחוב';
UPDATE "Show" SET "cast" = 'תום אבני, עידו טאקו / יונתן הורנצ''יק, מוטי כץ, שרה פון שוורצה' WHERE "slug" = 'החולה-ההודי';
UPDATE "Show" SET "cast" = 'רוני דלומי / גלית גיאת / אילי עלמני, חני נחמיאס, טל מוסרי, גל גולדשטיין / עומר קרן, שחר רז / מור חנסון, מתן שביט, דוית גביש / שיר אברמוב, שפי מרציאנו / דניאל חסין, מיקי פלג-רוטשטיין / עמית זיתון, אורי הוכמן / שמוליק כהן, הילה שלו / גל שטרית, רונית אפל / סיון קינר קיסינג׳ר, ניל משען / יובל שלומוביץ, אברהם סלקטר, רוברטו פולק / פיני קידרון, שירן הוברמן / איילת רובינסון' WHERE "slug" = 'בוסתן-ספרדי-2021';
UPDATE "Show" SET "cast" = 'נעמי הררי, נעמה אמית, ליא קניג, אושרת אינגדשט, אורלי זילברשץ, ליליאן ברטו, דוית גביש, נילי רוגל, כרמל נצר, רונית אפל, הגר נחמיאס' WHERE "slug" = 'הלילה-השנים-עשר';
UPDATE "Show" SET "cast" = 'רבקה מיכאלי, דני בסן, עדי כהן, אלונה ארז, תמר גלעדי, קרן טננבאום, ללי שמר, ורד פיקר, עופרי ביטרמן, ספיר ברייר, עמית שושני, גלעד שמואלי' WHERE "slug" = 'מחווה-לנעמי-שמר';
UPDATE "Show" SET "cast" = 'ליר כץ, אלכס קרול, דב רייזר, אורי הוכמן, ליאת גורן, ספיר אזולאי, ויטלי פרידלנד, הגר לוב' WHERE "slug" = 'הנערה-מהדואר';
UPDATE "Show" SET "cast" = 'צביקה הדר / דוד קיגלר, אסתי זקהיים, מיכאל אלוני / אורי דב יוסף בלופרב, דניאל מנוחין / ירדן ברכה, הילה שלו / אילי עלמני, דוית גביש / מיקי פלג רוטשטיין / יעל לבנטל, עמי סמולרצ׳יק, אביב כרמי, איה זמיר / מיקה פריינטי / אלונה שטריקס' WHERE "slug" = 'חתונה-מאוחרת';
UPDATE "Show" SET "cast" = 'חנה לסלאו, יגאל שדה, דאנה איבגי, ספיר אזולאי, מתן שביט, אלכס קרול, ויטלי פרידלנד, ישי בן משה, ניר זליחובסקי / אבישי מרידור, הילה שלו, דוית גביש, עודד לאופולד, שפי מרציאנו, ניל משען / אבישי מרידור, טל קלאי' WHERE "slug" = 'הסוחר-מוונציה';
UPDATE "Show" SET "cast" = 'שי אגוזי, שיא דרייגור קדמן, שירי לוטן, הראל מוראד' WHERE "slug" = 'קיצור-תהליכים';
UPDATE "Show" SET "cast" = 'עמוס תמם, קרן מור, מרים זוהר / ליאת גורן, שהם שיינר / ערן מור, יצחק חזקיה / אוהד שחר, נעמה שטרית / שרון כהן רז, אלון סנדלר / רועי רביב, אבי טרמין / דודו ניב, דולב אוחנה / יותם גת, מיכאל כורש, נועה טסה, יותם גת / אוהב אזולאי.' WHERE "slug" = 'אדיפוס';
UPDATE "Show" SET "cast" = 'שהם שיינר / מיכה סלקטר, אנדריאה שוורץ / כינרת לימוני / אולה שור סלקטר' WHERE "slug" = 'גרושים';
UPDATE "Show" SET "cast" = 'מיקי קם, אודיה קורן' WHERE "slug" = 'השותפה';
UPDATE "Show" SET "cast" = 'יובל סגל, יעל לבנטל / הגר טישמן, פיני קידרון, עמי סמולרצ׳יק, הגר טישמן / ספיר אזולאי, נדב ארטשיק, נויה אביגדור' WHERE "slug" = 'משכנתא';
UPDATE "Show" SET "cast" = 'אלונה סער, עופר חיון, יגאל שדה, אימרי ביטון, אבישי מרידור, מרינה שויף, הילה שלו, קורל קרואני' WHERE "slug" = 'מלאכים-בלבן';
UPDATE "Show" SET "cast" = 'קרן מור, אסף פרי, אנסטסיה פיין, דודו ניב, דן שפירא / שחף קהלאני, מורן ארביב גנס / פז כהן, טל וייס, יואב יחזקאלי / אמיר בנאי' WHERE "slug" = 'חשמלית-ושמה-תשוקה';
UPDATE "Show" SET "cast" = 'יערה לוי, נדב ארדיטי' WHERE "slug" = 'פציעות-קטנות';
UPDATE "Show" SET "cast" = 'דרור קרן, רבקה מיכאלי, אולה שור סלקטר, ערן מור, רוני נתנאל, אלון סנדלר, איה גרניט שבא, שמחה ברבירו, תום חודורוב, נדב אסולין, דודו ניב, דן שפירא' WHERE "slug" = 'הלוויה-חורפית';
UPDATE "Show" SET "cast" = 'חן גרטי / נוי הלפרין, גלעד מרחבי / עמית שושני, ערן מור / נדב נייטס, איה גרניט שבא / אסנת בן יהודה, מורן ארביב גנס / ירדן ניקפהמה, אלעד אטרקצ''י / תום חודורוב' WHERE "slug" = 'הציפור-הכחולה';
UPDATE "Show" SET "cast" = 'אסנת פישמן, תומר שרון, ליליאן ברטו, דב רייזר, מיקי פלג רוטשטיין, הגר טישמן סבג, אסף זלמנוביץ׳, תמיר גינזבורג, יארא זרייק' WHERE "slug" = 'פעולות-פשוטות';
UPDATE "Show" SET "cast" = 'יניב סויסה / יואב לוי, נטע גרטי / בת חן סבג, עידו ברטל, כינרת לימוני / אנדריאה שוורץ, ישי גולן, ערן מור, דויד בילנקה, לואי נופי, אנה חריט' WHERE "slug" = 'הריטריט';
UPDATE "Show" SET "cast" = 'יגאל שדה, אסף זלמנוביץ׳, רונית אפל, הילה שלו, ניר זליחובסקי, ניל משען, יואב מילשטיין, עדן ביטון / אופק זרקו, גל שטרית' WHERE "slug" = 'פינוקיו';
UPDATE "Show" SET "cast" = 'מרים זוהר / גילה אלמגור - אגמון , מיה לנדסמן, יצחק חזקיה / אוהד שחר, עומר עציון / גור קורן, ענבר דנון / ענבל בר-לב, אוריה יבלונובסקי / גלעד שמואלי, רוני נתנאל / נעם ברט' WHERE "slug" = 'צ׳ילבות';
UPDATE "Show" SET "cast" = 'לי בירן / עידו רוזנברג, יחזקאל לזרוב / צביקי לוין, מיכאל בן דוד, פיני קדרון / אורי הוכמן / גלעד קלטר, עדי כהן, אילי עלמני, רויטל זלצמן / מורן אהרוני, רונית אפל, מאיה לבני, טל קלאי / מושיק גלאמין, אלון זלוטקין / עמית קורן-סוסקינד / רועי אפלבאום, רוני מרחבי / תום אנטופולסקי, עמית קפון, רותם יהודה, איתי שלו לוגסי, עדן ביטון, ירדן בר אל, כפיר מדניצקי, שובל חכמון, עמית לוי, מאיה מדג׳ר, מאיה מור, עופרי אגמון, יהב סבג, בר בנימין, מתן קפלן, ליאור זמואלסון, איתי בר, אלדר לוי, אורי לביא, עדן אמסילי, סימון גנגי, דור אלדר, שון בסעד' WHERE "slug" = 'פריסילה-מלכת-המדבר';
UPDATE "Show" SET "cast" = 'טוביה צפיר, יונה אליאן קשת, נלי תגר / ריקי בליך, דניאל סבג, ניל משען' WHERE "slug" = 'להתראות-ותודה-על-הקרמשניט';
UPDATE "Show" SET "cast" = 'דביר בנדק, שרון כהן רז, רות אסרסאי, עופרי ביטרמן, מיכל עוזיאל, יוסף יצחק' WHERE "slug" = 'הלווייתן';
UPDATE "Show" SET "cast" = 'ליא קניג, גילת אנקורי, אורי הוכמן, ריקי בליך' WHERE "slug" = 'מרציפנים';
UPDATE "Show" SET "cast" = 'יגאל נאור, ישראל קטורזה, מיקי קם' WHERE "slug" = 'הג׳יגולו-מקונגו';
UPDATE "Show" SET "cast" = 'טלי אורן / שני שאולי, עופרי ביטרמן, רפאל עבאס, יניב סויסה / נדב אסולין, אוראל צברי / אודי גוטשלק, דניאל סטיופין / גארי נופין / שהם שיינר, אלעד אטרקצ''י, מאיה לבני / ליה גידור, מתן און ימי, ליאור בן יהודה / מיכל פרדקין, דור אוחיון / יעל דובר, אור משה / אדיר בובליל, גלעד מרחבי / דין גרבר, עופרי סלומון / שיר בודק, בר קליין / מיכל פרדקין, אופק זרקו / אנטולי שנפלד, גיא סטרובולסקי, טופז אבדנג / דניאל און ימי, אנטולי שנפלד / טל בן אהרון, עדי מיוחס / שיר בודק, יובל אבירם / אמיר אהרוני, שחף בוארון / דין רואס' WHERE "slug" = 'החבדניקים';

-- Nullify cast for shows that have no cast in local DB
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'According-to-Law';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'Can-you-beat-the-KGB';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'HANNAH';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'Mamachine';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'Mix-&-Match';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'אם-זה-אדם';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'בת-של-אבא';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'על-אם-הדרך';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'לא-שקט';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'פו-הדב';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'לא-סוף-העולם';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'שם-פרטי';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'מה-שקרה-לנו';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'אף-מילה-לאמא';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'זה-בסדר.';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'מי-כמוני';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'אש-בארזים';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'מי-שסוכתו-נופלת';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'אמא';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'כפר';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'פים-פם-פה';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'כנר-על-הגג-–-המחזמר';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'אין-לי-ארץ-אחרת-מופע-הצדעה-לאהוד-מנור';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'אני-פה-בגלל-אשתי';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'איך-לא-חשבתי-על-זה-קודם';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'שיר-של-אמונה-וכפירה';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'דיק-פיק';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'ימח-שמי';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'הלב-שלי-בחר';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'אמא-שלי-קראה-לי-רוטוויילר';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'אבא-יצא-מהקבוצה';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'בית-בעזה';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'הכל-נשאר-חי';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'שלא-יגמר-לי';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'אני-מכיר-רק-אחד-שמתנהג-ככה';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'הכי-בבית-בעולם';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'שחף-עודד-קוטלר';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'בין-קודש-לחולון';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'הכל-נשאר-במשפחה';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'ככה-יצאתי';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'הכל-אודות-איב';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'חנה-לסלאו-היא-ד-ר-רות-ווסטהיימר';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'אפס-ביחסי-אנוש';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'מפי-שמירה-אימבר';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'אור-לגויים';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'אנה-קרנינה';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'באר-שבסקיה';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'זוג-משמיים';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'פאק-בסיסטם';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'קיר-זכוכית';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'קצר-לילדים';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'איך-ג׳ירפה-ישנה';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'אמא-קוראז׳-וילדיה';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'ערב-שקופיות';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'רצח-במועדון-הטרנספר';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'נער-האופניים';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'אדום';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'אסתר';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'האמת';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'הסוף';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'עפרה';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'קרום';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'תהלה';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'לילה-–-סיפורה-של-לילה-מוראד';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'דמות-אב';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'דירה-לא-להשכיר';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'מראה-מעל-הגשר';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'בגלל-הרוח';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'הפרח-בגני';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'מיתה-טובה';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'מכתב-הקסם';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'שוקו-וניל';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'שושי-בחלל';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'שחקן-מחפש-במה';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'ערוץ-שטות-עשרה';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'אהבה-וחושך';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'הזוג-המוזר';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'הפנס-הסגול';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'לילה-ברומא';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'מסכת-גאולה';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'פינק-ליידי';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'מלכת-היופי-של-ירושלים';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'אהבה-בהפתעה';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'החטא-ועונשו';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'חנאל-ומכבית';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'סיור-מאחורי-הקלעים';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'פימה-ג׳קסון-ולהקתו';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'שוחט-בעקבות-אמדאוס';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'סיור-מאחורי-הקלעים-תיאטרון-בית-ליסין';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'ביבר-הזכוכית';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'אנטי-אייג׳ינג';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'קברט-ז׳בוטינסקי';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'אבהות';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'בילבי';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'היומן';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'המורה';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'העורף';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'לדפוק';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'נשמות';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'סלומה';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'עצבים';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'פצעים';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'שמואל';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'שמשון';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'דיסקו,-בייבי-!';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'מקליד-ה...';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'משרתם-של-שני-אדונים';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'לשחרר-את-נחמה';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'מותרת-לכל-אדם';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'כשאמא-באה-הנה-אריאל-הורוביץ-ו״האחיות-שמר-24״';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'החולד-הקטן';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'התשמע-קולי';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'סיפור-פשוט';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'הֱיֵה-שלום,-מר-הַפְמַן';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'האוצר-מתחת-לגשר';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'מישהו-לרוץ-איתו';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'גידול-ושמו-בועז-קומדיה-רומנטית-בקטע-דפוק';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'אקורד-סיום-למלחמה';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'אורות-קטנות';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'הורים-יקרים';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'מחכים-לגודו';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'שיעור-באהבה';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'המופע-הגלוי-של-גל-בנג׳ו-The-Banjo-Show';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'העלמה-והמוות';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'השוטר-אזולאי';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'סונטת-קרויצר';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'עוברת-בירושה';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'קסמים-בשחקים';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'מחווה-לדיוות-הגדולות';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'הפצוע-הישראלי';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'התחנה-האחרונה';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'יאקיש-ופופצ׳ה';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'משחקי-נישואים';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'צלילי-המוסיקה';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'תיכון-מגשימים';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'כביסה-מלוכלכת-TAKE-3';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'אבידן-ואלייזה-–-מופע-ספרותי';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'סיפור-הפרברים-–-המחזמר';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'מסעות-אודיסאוס';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'מצבים-בפוטנציה';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'אירלנד';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'אמדאוס';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'ארטיסט';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'הדיבוק';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'הסבתות';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'לאונרד';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'לילסדה';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'סביצ׳ה';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'קנאביס';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'קרנפים';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'המאסטר-(אלוף-הבונים-שלי)';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'זוגיות-AI';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'ריצ׳רד-III';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'החברות-של-אלוהים';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'בתחילת-קיץ-1970';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'האוויר-הוא-של-כולם';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'יהודים-רעים';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'שותפים-לנצח';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'תעלולי-סקפן';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'משחקים-בחצר-האחורית';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'בחורים-טובים';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'גבירתי-הנאווה';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'טובעים-השניים';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'מקומות-שמורים';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'רוחל׳ה-מתחתנת';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'יעקובי-ולידנטל';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'אבדוֹת-ומציאוּת';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'בוז׳ולה';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'דרייפוס';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'יהושולה';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'להתעורר';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'עיגולים-של-שמחה';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'אחינועם-ואני';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'פריסילה-מלכת-המדבר-סיור-מאחורי-הקסם!';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'משתגעים-מאהבה';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'הברונית-רוטשילד';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'פריקואל-וסיקואל-יורשים-כת';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'נישואים-גרעיניים';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'אקספוז׳ר';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'דתילונים';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'מהפכניות';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'פליידייט';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'פופלינדה-בממלכת-הדמיון';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'רוזנקרנץ-וגילדנשטרן-מתים';
UPDATE "Show" SET "cast" = NULL WHERE "slug" = 'השתקפויות';
