// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

// Load .env.local first (Next.js convention for local dev), then .env as fallback
dotenv.config({ path: ".env.local", override: true });
dotenv.config({ path: ".env" });

const databaseUrl = process.env["DATABASE_URL"];
const directDatabaseUrl =
  process.env["DIRECT_DATABASE_URL"] ?? process.env["POSTGRES_URL_NON_POOLING"];

function deriveDirectUrlFromPooler(url?: string) {
  if (!url) {
    return undefined;
  }

  try {
    const parsedUrl = new URL(url);
    if (!parsedUrl.hostname.includes("-pooler.")) {
      return undefined;
    }

    parsedUrl.hostname = parsedUrl.hostname.replace("-pooler.", ".");
    return parsedUrl.toString();
  } catch {
    return undefined;
  }
}

const derivedDirectDatabaseUrl = deriveDirectUrlFromPooler(databaseUrl);

/**
 * Append `connect_timeout` to a PostgreSQL connection URL so Prisma Migrate
 * has enough time for Neon serverless cold-starts (default libpq timeout is
 * too short for suspended computes).
 */
function withConnectTimeout(url?: string, seconds = 30): string | undefined {
  if (!url) return undefined;
  try {
    const parsed = new URL(url);
    if (!parsed.searchParams.has("connect_timeout")) {
      parsed.searchParams.set("connect_timeout", String(seconds));
    }
    return parsed.toString();
  } catch {
    return url;
  }
}

const migrationUrl = withConnectTimeout(
  directDatabaseUrl ?? derivedDirectDatabaseUrl ?? databaseUrl,
);

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node prisma/seed.js",
  },
  datasource: {
    // Prisma Migrate needs a direct Postgres connection (not a pooled `-pooler` URL)
    // for advisory locks. We also add connect_timeout=30 to handle Neon cold starts.
    url: migrationUrl,
  },
});
