// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const databaseUrl = process.env["DATABASE_URL"];
const directDatabaseUrl = process.env["DIRECT_DATABASE_URL"];

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node prisma/seed.js",
  },
  datasource: {
    // Prisma Migrate needs a direct Postgres connection (not a pooled `-pooler` URL)
    // for advisory locks. Fall back to DATABASE_URL for local/dev convenience.
    url: directDatabaseUrl ?? databaseUrl,
  },
});
