// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const databaseUrl = process.env["DATABASE_URL"];
const directDatabaseUrl =
  process.env["DIRECT_DATABASE_URL"] ?? process.env["POSTGRES_URL_NON_POOLING"];

function deriveDirectUrlFromPooler(url?: string) {
  if (!url) {
    return undefined;
  }

  try {
    const parsedUrl = new URL(url);
    if (!parsedUrl.hostname.includes("-pooler.")) {
      return undefined;
    }

    parsedUrl.hostname = parsedUrl.hostname.replace("-pooler.", ".");
    return parsedUrl.toString();
  } catch {
    return undefined;
  }
}

const derivedDirectDatabaseUrl = deriveDirectUrlFromPooler(databaseUrl);

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node prisma/seed.js",
  },
  datasource: {
    // Prisma Migrate needs a direct Postgres connection (not a pooled `-pooler` URL)
    // for advisory locks.
    url: directDatabaseUrl ?? derivedDirectDatabaseUrl ?? databaseUrl,
  },
});
