-- CreateTable
CREATE TABLE "Actor" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "image" TEXT,

    CONSTRAINT "Actor_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ShowActor" (
    "showId" INTEGER NOT NULL,
    "actorId" INTEGER NOT NULL,

    CONSTRAINT "ShowActor_pkey" PRIMARY KEY ("showId","actorId")
);

-- CreateIndex
CREATE UNIQUE INDEX "Actor_name_key" ON "Actor"("name");

-- CreateIndex
CREATE UNIQUE INDEX "Actor_slug_key" ON "Actor"("slug");

-- AddForeignKey
ALTER TABLE "ShowActor" ADD CONSTRAINT "ShowActor_showId_fkey" FOREIGN KEY ("showId") REFERENCES "Show"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ShowActor" ADD CONSTRAINT "ShowActor_actorId_fkey" FOREIGN KEY ("actorId") REFERENCES "Actor"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- Seed actors
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('גילה אלמגור', 'גילה-אלמגור', '/actors/גילה-אלמגור.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('גילת אנקורי', 'גילת-אנקורי', '/actors/גילת-אנקורי.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('דניאל גל', 'דניאל-גל', '/actors/דניאל-גל.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('טל מוסרי', 'טל-מוסרי', '/actors/טל-מוסרי.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('טלי אורן', 'טלי-אורן', '/actors/טלי-אורן.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('לי בירן', 'לי-בירן', '/actors/לי-בירן.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('לימור גולדשטיין', 'לימור-גולדשטיין', '/actors/לימור-גולדשטיין.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('מגי אזרזר', 'מגי-אזרזר', '/actors/מגי-אזרזר.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('מולי שולמן', 'מולי-שולמן', '/actors/מולי-שולמן.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('נעם קלינשטיין', 'נעם-קלינשטיין', '/actors/נעם-קלינשטיין.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('נעמי הררי', 'נעמי-הררי', '/actors/נעמי-הררי.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('עירית ענבי', 'עירית-ענבי', '/actors/עירית-ענבי.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('רביב כנר', 'רביב-כנר', '/actors/רביב-כנר.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('רוני דלומי', 'רוני-דלומי', '/actors/רוני-דלומי.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('תום אבני', 'תום-אבני', '/actors/תום-אבני.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('אביגיל הררי', 'אביגיל-הררי', '/actors/אביגיל-הררי.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('אבי קושניר', 'אבי-קושניר', '/actors/אבי-קושניר.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('אודיה קורן', 'אודיה-קורן', '/actors/אודיה-קורן.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('אולה שור סלקטר', 'אולה-שור-סלקטר', '/actors/אולה-שור-סלקטר.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('אוראל צברי', 'אוראל-צברי', '/actors/אוראל-צברי.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('אלון סנדלר', 'אלון-סנדלר', '/actors/אלון-סנדלר.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('אלי גורנשטיין', 'אלי-גורנשטיין', '/actors/אלי-גורנשטיין.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('אלכס קרול', 'אלכס-קרול', '/actors/אלכס-קרול.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('אלעד אטרקצ׳י', 'אלעד-אטרקצ׳י', '/actors/אלעד-אטרקצ׳י.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('גלית גיאת', 'גלית-גיאת', '/actors/גלית-גיאת.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('דביר בנדק', 'דביר-בנדק', '/actors/דביר-בנדק.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('דור הררי', 'דור-הררי', '/actors/דור-הררי.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('דניאל סטיופין', 'דניאל-סטיופין', '/actors/דניאל-סטיופין.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('דרור קרן', 'דרור-קרן', '/actors/דרור-קרן.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('חן גרטי', 'חן-גרטי', '/actors/חן-גרטי.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('חנה לסלאו', 'חנה-לסלאו', '/actors/חנה-לסלאו.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('חני נחמיאס', 'חני-נחמיאס', '/actors/חני-נחמיאס.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('טל גרושקה', 'טל-גרושקה', '/actors/טל-גרושקה.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('יונה אליאן קשת', 'יונה-אליאן-קשת', '/actors/יונה-אליאן-קשת.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('יורם טולדנו', 'יורם-טולדנו', '/actors/יורם-טולדנו.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('יניב סויסה', 'יניב-סויסה', '/actors/יניב-סויסה.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('יעל לבנטל', 'יעל-לבנטל', '/actors/יעל-לבנטל.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('יפתח קליין', 'יפתח-קליין', '/actors/יפתח-קליין.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('כינרת לימוני', 'כינרת-לימוני', '/actors/כינרת-לימוני.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('ליאור אשכנזי', 'ליאור-אשכנזי', '/actors/ליאור-אשכנזי.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('לינוי כהן', 'לינוי-כהן', '/actors/לינוי-כהן.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('לֿאורה ריבלין', 'לֿאורה-ריבלין', '/actors/לֿאורה-ריבלין.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('מיקה צור', 'מיקה-צור', '/actors/מיקה-צור.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('משי קליינשטיין', 'משי-קליינשטיין', '/actors/משי-קליינשטיין.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('נדב אסולין', 'נדב-אסולין', '/actors/נדב-אסולין.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('נדב נייטס', 'נדב-נייטס', '/actors/נדב-נייטס.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('נורמן עיסא', 'נורמן-עיסא', '/actors/נורמן-עיסא.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('נטע גרטי', 'נטע-גרטי', '/actors/נטע-גרטי.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('נתן דטנר', 'נתן-דטנר', '/actors/נתן-דטנר.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('סנדרה שדה', 'סנדרה-שדה', '/actors/סנדרה-שדה.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('עידו רוזנברג', 'עידו-רוזנברג', '/actors/עידו-רוזנברג.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('עידן אלתרמן', 'עידן-אלתרמן', '/actors/עידן-אלתרמן.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('עמוס תמם', 'עמוס-תמם', '/actors/עמוס-תמם.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('עופרי ביטרמן', 'עופרי-ביטרמן', '/actors/עופרי-ביטרמן.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('צחי הלוי', 'צחי-הלוי', '/actors/צחי-הלוי.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('ציפי שביט', 'ציפי-שביט', '/actors/ציפי-שביט.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('קרן מור', 'קרן-מור', '/actors/קרן-מור.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('רבקה מיכאלי', 'רבקה-מיכאלי', '/actors/רבקה-מיכאלי.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('רמי ברוך', 'רמי-ברוך', '/actors/רמי-ברוך.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('רן דנקר', 'רן-דנקר', '/actors/רן-דנקר.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('רפאל עבאס', 'רפאל-עבאס', '/actors/רפאל-עבאס.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('ריקי בליך', 'ריקי-בליך', '/actors/ריקי-בליך.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('תום חודורוב', 'תום-חודורוב', '/actors/תום-חודורוב.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('תם גל', 'תם-גל', '/actors/תם-גל.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('ליא קניג', 'ליא-קניג', '/actors/ליא-קניג.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('מיקי קם', 'מיקי-קם', '/actors/מיקי-קם.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";
INSERT INTO "Actor" ("name", "slug", "image") VALUES ('צביקה הדר', 'צביקה-הדר', '/actors/צביקה-הדר.webp') ON CONFLICT ("name") DO UPDATE SET "slug" = EXCLUDED."slug", "image" = EXCLUDED."image";

-- Seed actor-show associations
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'מישהו-שר-את-זה-קודם' AND a."name" = 'אודיה קורן' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'מישהו-שר-את-זה-קודם' AND a."name" = 'אלון סנדלר' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'מישהו-שר-את-זה-קודם' AND a."name" = 'חן גרטי' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'מישהו-שר-את-זה-קודם' AND a."name" = 'יניב סויסה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'מישהו-שר-את-זה-קודם' AND a."name" = 'עופרי ביטרמן' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'מישהו-שר-את-זה-קודם' AND a."name" = 'תום חודורוב' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'קברט' AND a."name" = 'כינרת לימוני' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'קברט' AND a."name" = 'נדב נייטס' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'קברט' AND a."name" = 'רן דנקר' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'לנקות-את-הראש' AND a."name" = 'עופרי ביטרמן' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'מי-בעד' AND a."name" = 'אביגיל הררי' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'מי-בעד' AND a."name" = 'כינרת לימוני' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'מי-בעד' AND a."name" = 'נדב אסולין' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'גרושים' AND a."name" = 'אולה שור סלקטר' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'גרושים' AND a."name" = 'כינרת לימוני' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'הבן-של-מושיקו-הגדול' AND a."name" = 'עמוס תמם' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'סוס-אחד-נכנס-לבר' AND a."name" = 'דרור קרן' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'החבדניקים' AND a."name" = 'טלי אורן' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'החבדניקים' AND a."name" = 'אוראל צברי' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'החבדניקים' AND a."name" = 'דניאל סטיופין' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'החבדניקים' AND a."name" = 'יניב סויסה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'החבדניקים' AND a."name" = 'נדב אסולין' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'החבדניקים' AND a."name" = 'עופרי ביטרמן' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'החבדניקים' AND a."name" = 'רפאל עבאס' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'החולה-ההודי' AND a."name" = 'תום אבני' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'צ׳ילבות' AND a."name" = 'גילה אלמגור' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'הנפש-הטובה-מסצ׳ואן' AND a."name" = 'תום אבני' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'הנפש-הטובה-מסצ׳ואן' AND a."name" = 'אביגיל הררי' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'הנפש-הטובה-מסצ׳ואן' AND a."name" = 'רפאל עבאס' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'פיטר-פן' AND a."name" = 'אלון סנדלר' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'פיטר-פן' AND a."name" = 'נדב נייטס' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'פיטר-פן' AND a."name" = 'עופרי ביטרמן' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'פיטר-פן' AND a."name" = 'תום חודורוב' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'הציפור-הכחולה' AND a."name" = 'חן גרטי' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'הציפור-הכחולה' AND a."name" = 'נדב נייטס' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'הציפור-הכחולה' AND a."name" = 'תום חודורוב' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'עוץ-לי-גוץ-לי' AND a."name" = 'אלון סנדלר' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'עוץ-לי-גוץ-לי' AND a."name" = 'אלי גורנשטיין' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'עוץ-לי-גוץ-לי' AND a."name" = 'נדב נייטס' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'עוץ-לי-גוץ-לי' AND a."name" = 'עופרי ביטרמן' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'עוץ-לי-גוץ-לי' AND a."name" = 'רמי ברוך' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'חשמלית-ושמה-תשוקה' AND a."name" = 'קרן מור' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'היי-אוון-הנסן' AND a."name" = 'טלי אורן' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'היי-אוון-הנסן' AND a."name" = 'אולה שור סלקטר' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'היי-אוון-הנסן' AND a."name" = 'אלון סנדלר' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'היי-אוון-הנסן' AND a."name" = 'יניב סויסה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'היי-אוון-הנסן' AND a."name" = 'רפאל עבאס' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'אדיפוס' AND a."name" = 'אלון סנדלר' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'אדיפוס' AND a."name" = 'עמוס תמם' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'אדיפוס' AND a."name" = 'קרן מור' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'זינגר' AND a."name" = 'נדב נייטס' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'זינגר' AND a."name" = 'עמוס תמם' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'זינגר' AND a."name" = 'רמי ברוך' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'מיקי-מציל' AND a."name" = 'תום חודורוב' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'מיקי-מציל' AND a."name" = 'תם גל' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'הריטריט' AND a."name" = 'יניב סויסה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'הריטריט' AND a."name" = 'כינרת לימוני' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'הריטריט' AND a."name" = 'נטע גרטי' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'כל-הדברים-הטובים' AND a."name" = 'דביר בנדק' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'לילה-טוב-אמא' AND a."name" = 'אודיה קורן' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'לילה-טוב-אמא' AND a."name" = 'נטע גרטי' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'נעמי-ונורמה' AND a."name" = 'נדב אסולין' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'נעמי-ונורמה' AND a."name" = 'רבקה מיכאלי' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'לא-הייתם-צריכים' AND a."name" = 'אלון סנדלר' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'לא-הייתם-צריכים' AND a."name" = 'סנדרה שדה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'לא-הייתם-צריכים' AND a."name" = 'רמי ברוך' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'לא-הייתם-צריכים' AND a."name" = 'רפאל עבאס' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'האבא' AND a."name" = 'דביר בנדק' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'הלוויה-חורפית' AND a."name" = 'אולה שור סלקטר' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'הלוויה-חורפית' AND a."name" = 'אלון סנדלר' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'הלוויה-חורפית' AND a."name" = 'דרור קרן' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'הלוויה-חורפית' AND a."name" = 'נדב אסולין' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'הלוויה-חורפית' AND a."name" = 'רבקה מיכאלי' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'הלוויה-חורפית' AND a."name" = 'תום חודורוב' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'הלווייתן' AND a."name" = 'דביר בנדק' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'הלווייתן' AND a."name" = 'עופרי ביטרמן' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'מה-קרה-לעולם' AND a."name" = 'אודיה קורן' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'מה-קרה-לעולם' AND a."name" = 'רמי ברוך' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'מדיאה' AND a."name" = 'כינרת לימוני' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'מדיאה' AND a."name" = 'עמוס תמם' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'השותפה' AND a."name" = 'אודיה קורן' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'השותפה' AND a."name" = 'מיקי קם' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'איש-הגשם' AND a."name" = 'דביר בנדק' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'טרטיף' AND a."name" = 'אולה שור סלקטר' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'טרטיף' AND a."name" = 'דרור קרן' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'טרטיף' AND a."name" = 'חן גרטי' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'טרטיף' AND a."name" = 'נדב נייטס' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'טרטיף' AND a."name" = 'עופרי ביטרמן' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'מעבר-לדלת' AND a."name" = 'יעל לבנטל' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'פריסילה-מלכת-המדבר' AND a."name" = 'לי בירן' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'פריסילה-מלכת-המדבר' AND a."name" = 'עידו רוזנברג' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'הנערה-מהדואר' AND a."name" = 'אלכס קרול' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'משכנתא' AND a."name" = 'יעל לבנטל' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'הג׳יגולו-מקונגו' AND a."name" = 'מיקי קם' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'משהו-טוב' AND a."name" = 'נעמי הררי' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'משהו-טוב' AND a."name" = 'ליא קניג' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'הערת-שוליים' AND a."name" = 'גילת אנקורי' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'הערת-שוליים' AND a."name" = 'נעמי הררי' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'הערת-שוליים' AND a."name" = 'יפתח קליין' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'הערת-שוליים' AND a."name" = 'צחי הלוי' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'הערת-שוליים' AND a."name" = 'ריקי בליך' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'מרציפנים' AND a."name" = 'גילת אנקורי' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'מרציפנים' AND a."name" = 'ריקי בליך' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'מרציפנים' AND a."name" = 'ליא קניג' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'בית-בובות' AND a."name" = 'ריקי בליך' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'מי-את-חושבת-שאת' AND a."name" = 'יעל לבנטל' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'מי-את-חושבת-שאת' AND a."name" = 'ריקי בליך' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'הלילה-השנים-עשר' AND a."name" = 'נעמי הררי' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'הלילה-השנים-עשר' AND a."name" = 'ליא קניג' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'קזבלן' AND a."name" = 'טל מוסרי' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'מעגל-הגיר-הקווקזי' AND a."name" = 'אלכס קרול' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'מעגל-הגיר-הקווקזי' AND a."name" = 'נורמן עיסא' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'רומי-+-ג׳ולייט' AND a."name" = 'נעמי הררי' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'סיפור-הפרברים-–-המחזמר' AND a."name" = 'מגי אזרזר' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'סיפור-הפרברים-–-המחזמר' AND a."name" = 'רביב כנר' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'סיפור-הפרברים-–-המחזמר' AND a."name" = 'דור הררי' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'סיפור-הפרברים-–-המחזמר' AND a."name" = 'לינוי כהן' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'לילה-ברומא' AND a."name" = 'מולי שולמן' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'לילה-ברומא' AND a."name" = 'קרן מור' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'בין-קודש-לחולון' AND a."name" = 'לימור גולדשטיין' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'בין-קודש-לחולון' AND a."name" = 'אבי קושניר' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'אמדאוס' AND a."name" = 'טל גרושקה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'אמדאוס' AND a."name" = 'ליאור אשכנזי' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'קרנפים' AND a."name" = 'מולי שולמן' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'אפס-ביחסי-אנוש' AND a."name" = 'מגי אזרזר' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'אפס-ביחסי-אנוש' AND a."name" = 'קרן מור' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'אור-לגויים' AND a."name" = 'אבי קושניר' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'הכל-אודות-איב' AND a."name" = 'מגי אזרזר' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'אף-מילה-לאמא' AND a."name" = 'לימור גולדשטיין' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'אף-מילה-לאמא' AND a."name" = 'מולי שולמן' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'אף-מילה-לאמא' AND a."name" = 'קרן מור' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'חנאל-ומכבית' AND a."name" = 'קרן מור' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'מלכת-היופי-של-ירושלים' AND a."name" = 'דניאל גל' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'מלכת-היופי-של-ירושלים' AND a."name" = 'יורם טולדנו' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'המאסטר-(אלוף-הבונים-שלי)' AND a."name" = 'יפתח קליין' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'לשחרר-את-נחמה' AND a."name" = 'עירית ענבי' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'לשחרר-את-נחמה' AND a."name" = 'עידן אלתרמן' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'לשחרר-את-נחמה' AND a."name" = 'ציפי שביט' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'הזוג-המוזר' AND a."name" = 'עידן אלתרמן' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'היומן' AND a."name" = 'גילה אלמגור' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'היומן' AND a."name" = 'רוני דלומי' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'סביצ׳ה' AND a."name" = 'יעל לבנטל' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'סביצ׳ה' AND a."name" = 'עידן אלתרמן' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'גבירתי-הנאווה' AND a."name" = 'אלי גורנשטיין' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'גבירתי-הנאווה' AND a."name" = 'מיקה צור' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'גבירתי-הנאווה' AND a."name" = 'נתן דטנר' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'מראה-מעל-הגשר' AND a."name" = 'אלי גורנשטיין' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'מראה-מעל-הגשר' AND a."name" = 'נתן דטנר' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'כנר-על-הגג-–-המחזמר' AND a."name" = 'נתן דטנר' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'כנר-על-הגג-–-המחזמר' AND a."name" = 'סנדרה שדה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'רוחל׳ה-מתחתנת' AND a."name" = 'נתן דטנר' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'מחווה-לנעמי-שמר' AND a."name" = 'עופרי ביטרמן' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'מחווה-לנעמי-שמר' AND a."name" = 'רבקה מיכאלי' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'רינגו' AND a."name" = 'חן גרטי' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'רינגו' AND a."name" = 'תום חודורוב' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'רינגו' AND a."name" = 'תם גל' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'אוי-אלוהים' AND a."name" = 'יעל לבנטל' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'אוי-אלוהים' AND a."name" = 'נורמן עיסא' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'אוי-אלוהים' AND a."name" = 'ריקי בליך' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'בוסתן-ספרדי-2021' AND a."name" = 'טל מוסרי' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'בוסתן-ספרדי-2021' AND a."name" = 'רוני דלומי' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'בוסתן-ספרדי-2021' AND a."name" = 'גלית גיאת' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'בוסתן-ספרדי-2021' AND a."name" = 'חני נחמיאס' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'הסוחר-מוונציה' AND a."name" = 'אלכס קרול' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'הסוחר-מוונציה' AND a."name" = 'חנה לסלאו' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'חתונה-מאוחרת' AND a."name" = 'יעל לבנטל' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'חתונה-מאוחרת' AND a."name" = 'צביקה הדר' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'להתראות-ותודה-על-הקרמשניט' AND a."name" = 'יונה אליאן קשת' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'להתראות-ותודה-על-הקרמשניט' AND a."name" = 'ריקי בליך' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'תרקדי-איתי' AND a."name" = 'צביקה הדר' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'אמא' AND a."name" = 'דניאל גל' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'הכל-נשאר-במשפחה' AND a."name" = 'סנדרה שדה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'אין-לי-ארץ-אחרת-מופע-הצדעה-לאהוד-מנור' AND a."name" = 'נתן דטנר' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'אין-לי-ארץ-אחרת-מופע-הצדעה-לאהוד-מנור' AND a."name" = 'מיקי קם' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'הסוף' AND a."name" = 'עידן אלתרמן' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'הסוף' AND a."name" = 'רפאל עבאס' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'אשכבה' AND a."name" = 'נדב אסולין' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'אשכבה' AND a."name" = 'רמי ברוך' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'אהבה-מודרנית' AND a."name" = 'טלי אורן' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'אהבה-מודרנית' AND a."name" = 'מולי שולמן' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'אנני' AND a."name" = 'תם גל' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'מצחיקונת-–-Funny-Girl' AND a."name" = 'תם גל' ON CONFLICT DO NOTHING;
INSERT INTO "ShowActor" ("showId", "actorId") SELECT s."id", a."id" FROM "Show" s, "Actor" a WHERE s."slug" = 'מיקה-שלי' AND a."name" = 'גילת אנקורי' ON CONFLICT DO NOTHING;
