-- Migration: Add new tmuna shows
-- Generated on 2026-02-27T01:30:19.645Z
-- This migration is idempotent (uses ON CONFLICT DO NOTHING).

-- ============================================================
-- 1. Insert Genres
-- ============================================================
INSERT INTO "Genre" (name) VALUES ('אינטימי') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Genre" (name) VALUES ('דרמה') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Genre" (name) VALUES ('דרמה קומית') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Genre" (name) VALUES ('ילדים') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Genre" (name) VALUES ('מוזיקלי') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Genre" (name) VALUES ('מרגש') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Genre" (name) VALUES ('סאטירה') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Genre" (name) VALUES ('פנטזיה') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Genre" (name) VALUES ('קומדיה') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Genre" (name) VALUES ('קומדיה שחורה') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Genre" (name) VALUES ('רומנטי') ON CONFLICT (name) DO NOTHING;

-- ============================================================
-- 2. Insert Shows
-- ============================================================
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description) VALUES ('?Can you beat the KGB', 'Can-you-beat-the-KGB', 'תיאטרון תמונע', 120, 'אירוע תיאטרוני חתרני המשלב משחק שולחן, בו הקהל מתמודד עם שאלות מוסריות ויוצר רשת סוכנים למען חברה טובה יותר.', 'משחק שולחן השתתפותי בעקבות חייו ומותו של אלכסיי נבלני. באירוע תיאטרוני חתרני בשיתוף הקהל נתחקה אחרי פעולותיו ונבצע משימות שכל אחת מהן תקרב אותנו אל המטרה – הקמת רשת סוכנים לבניית חברה סולידרית, הפועלת בכבוד, צדק ואהבה.') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description) VALUES ('אבהות', 'אבהות', 'תיאטרון תמונע', 75, 'יצירת תיאטרון תנועה דוקומנטרית המציעה חקירה מעמיקה של אבהות דרך סיפורים אישיים ותנועה, בין רגש להומור.', 'שלושה גברים על במה – אב לפני לידת ילדו הראשון, אב צעיר, ואב-סב – מנסים להשיב על השאלה האם להיות אבא. המופע נע בין סיפורים אישיים ומבוסס על ראיונות מוקלטים עם אנשים על האבות שלהם או האבות שהם.') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description) VALUES ('אדום', 'אדום', 'תיאטרון תמונע', 70, 'דרמה עוצמתית על התמודדות עם ערכים אמנותיים מול לחצים מסחריים, המציעה חוויה רב חושית מרתקת.', 'דרמה לחיים ומוות על אומנות חברות ופער הדורות, בה הצייר מארק רות''קו מתמודד עם האקט המסחרי מול ערכיו האומנותיים. המחזה כולל דיאלוגים טעונים ויכוחים פילוסופיים, המשרטטים את דיוקן האמן הבלתי מתפשר.') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description) VALUES ('איך לא חשבתי על זה קודם', 'איך-לא-חשבתי-על-זה-קודם', 'תיאטרון תמונע', 75, 'קומדיה שחורה המציעה מבט עדין על זיקנה, בדידות וההרהורים על החיים, דרך דיאלוגים מרגשים ומפגשים בלתי צפויים.', 'תומס, קשיש מר נפש, נרגן ומיזנטרופ, נפגש עם דמויות שונות שמביאות אותו לחשוב על החיים, המוות והבדידות. המפגשים חושפים סוד מעברם המשותף שיטלטל את תומס.') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description) VALUES ('בילבי', 'בילבי', 'תיאטרון תמונע', 60, 'הצגה קסומה על אחים שמגלים את הכוח של דמיון וחברות דרך בילבי, ילדה שמביאה צבע לעולם האפור שלהם.', 'טומי ואנה, שני אחים בעולם שחור לבן, פוגשים את בילבי, ילדה מצחיקה עם קוף מדבר, שמביאה צבע לחייהם ופותחת בפניהם עולם של הרפתקאות ודמיון.') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description) VALUES ('דירה לא להשכיר', 'דירה-לא-להשכיר', 'תיאטרון תמונע', 60, 'דירה לא להשכיר היא הצגה מרגשת על פליטים שמעלים מופע במבנה נטוש, במטרה למצוא נחמה דרך אמנות לאחר מלחמה קשה.', 'ארבעה פליטים ששרדו מלחמה קשה מנסים למצוא נחמה ומפלט דרך הצגה שהם מעלים במבנה נטוש. המפגש עם קטעי הספרות והמחזות מסייע להם להתמודד עם החוויות הקשות שעברו.') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description) VALUES ('החולד הקטן', 'החולד-הקטן', 'תיאטרון תמונע', 50, 'החולד הקטן היא הצגת ילדים מוסיקלית ומצחיקה, המציעה חוויה חינוכית ומבדרת על חיפוש אחר האמת והבנת העולם.', 'ההצגה מציגה את סיפורו של חולד קטן שמחפש את מי שעשה לו על הראש. במהלך המסע, הוא פוגש חיות שונות ולומד על העולם שסביבו, כל זאת תוך שילוב של דיאלוגים שנונים, שירה וריקוד.') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description) VALUES ('הכל נשאר חי', 'הכל-נשאר-חי', 'תיאטרון תמונע', 60, 'הכל נשאר חי הוא סיפור אינטימי על אהבה והתמודדות עם פוסט טראומה, המציע מבט ייחודי על ההשפעה של מלחמה על הלוחם ובני משפחתו.', 'אישה אוהבת יוצאת למסע למצוא תרופה לבעלה ששב זועף משדה הקרב. דרך אגדה יפנית עתיקה, ההצגה עוסקת בטראומה משנית ומציעה מבט ייחודי על פוסט טראומה דרך עיניה של בת הזוג.') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description) VALUES ('המורה', 'המורה', 'תיאטרון תמונע', 80, 'הצגה מרתקת על מורה צעירה המלווה תלמידים למסע לפולין, שבו טראומות מהעבר צפות ועולות, בשילוב סאונד היפר-ריאליסטי.', 'אנחנו באוטובוס מספר 2 במסע לפולין. המורה הצעירה מלווה 37 תלמידים חרמנים בני שבע-עשרה, והמסע הולך להסתבך. שכבות טראומות מאיימות לצוף כשתאונה אחת פותחת את מה שכולם הדחיקו. ההצגה שואלת שאלות נוקבות על זיכרון והדחקה, חינוך וטראומה, ומציעה מסע חושי, רגשי ומצחיק.') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description) VALUES ('הפצוע הישראלי', 'הפצוע-הישראלי', 'תיאטרון תמונע', 70, 'קומדיה סאטירית מבריקה המגוללת את סיפורו של פצוע מסתורי בבית החולים, תוך חקירת טראומות עבר והשפעתן על החיים.', 'קומדיה סאטירית על פצוע מסתורי שוכב בבית החולים. עם כל מבקר שמגיע אליו, מתפתחת התעלומה סביב זהותו ונסיבות הגעתו. המחזה בוחן את הדרכים בהן אמנות, פוליטיקה ורוחניות עוזרות להתמודד עם טראומות עבר, ומציג סיפור ישראלי על אנשים המנסים לברוח מהסיפור שלהם רק כדי לגלות שהם כותבים אותו מחדש.') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description) VALUES ('יהושולה', 'יהושולה', 'תיאטרון תמונע', 70, 'הצגה ייחודית על זוג פנסיונרים המגלים את הסדקים בזוגיותם, באמצעות מסכות ובובות, ללא מילים.', 'זוג פנסיונרים חווים שגרה אינטימית עד שהמציאות פורצת לעולמם. הסדקים ביניהם נחשפים דרך מסכות ובובות, ללא מילים. ההצגה נוגעת בנושאים של זוגיות, כאב ותשוקה, ומביאה לקהל חוויה רגשית עמוקה.') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description) VALUES ('ימח שמי', 'ימח-שמי', 'תיאטרון תמונע', 80, 'מופע קברטי מצחיק המעלה שאלות על שינוי וכפרה, כאשר היטלר מתמודד עם עברו בגיהנום.', 'היטלר מוצא את עצמו בגיהנום, מעלה שאלות על שינוי וכפרה. מופע קברטי המשלב הומור עם נושא כבד, מציע חוויה מצחיקה ומעוררת מחשבה על אפשרות שינויו של הצורר הנורא.') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description) VALUES ('כביסה מלוכלכת | TAKE 3', 'כביסה-מלוכלכת-TAKE-3', 'תיאטרון תמונע', 60, 'הצגה רפיטטיבית ומעוררת מחשבה על חיים, זיכרון ואינטימיות, המתרחשת במפעל כביסה.', 'שתי נשים פועלות במפעל כביסה, חוויה רפיטטיבית של סחיטה וספיגה, המציעה לצופה להיכנס אל תוך המכונה של החיים. ההצגה עוסקת בזיכרון, אהבה ואינטימיות, ומזמינה את הקהל לבחון את ערכיו.') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description) VALUES ('לא סוף העולם', 'לא-סוף-העולם', 'תיאטרון תמונע', 75, 'פנטזיה רומנטית על מורה שמתאהב בתלמידה לשעבר, במסע מדעי להוכחת תיאוריה על העולם השטוח.', 'מיכאל, מורה למדעים, מתאהב בנועה, תלמידה לשעבר, המאוהבת בכוכב רשת. הם יוצאים למסע אל סוף העולם כדי להוכיח שהעולם שטוח, בעוד זוהר שואף לקריירה פוליטית. ההצגה מציעה פנטזיה רומנטית עם נגיעות מדעיות.') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description) VALUES ('לא שקט', 'לא-שקט', 'תיאטרון תמונע', 60, 'לא שקט מציע הצגת יחיד מרגשת בה אבי גולומב מתמודד עם חוויות כואבות מהעבר בעקבות הפסקת הריון, תוך חיפוש אחר זיכרונות שהודחקו.', 'הצגת יחיד מאת ובביצוע אבי גולומב על חוויית הגבר בהפסקת הריון של אשתו תוך ניסיון להיזכר באירועים שהדחיק מאותה תקופה.') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description) VALUES ('לאונרד', 'לאונרד', 'תיאטרון תמונע', 70, 'לאונרד הוא מופע תיאטרוני מרגש המשלב שירה וכתיבה של לאונרד כהן, המציע מבט מעמיק על חייו ועל השפעתם על התרבות.', 'מסע אל תוך הכתיבה של לאונרד כהן המשורר, שמציג את חייו וחוויותיו דרך שיריו המוכרים, ומזמין את הקהל להרהר במלחמות, אהבה ואלוהים.') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description) VALUES ('מהפכניות', 'מהפכניות', 'תיאטרון תמונע', 80, 'מהפכניות מציעה פרשנות חדשה על ההיסטוריה, בה היא מדגישה את תפקידן של נשים מאחורי גברים ידועים, ומביאה את סיפורן אל קדמת הבמה.', 'המחזה חודר לחדר המיטות של הזוג פרויד ומציג את תרומתן של נשים מההיסטוריה למהפכות, תוך הבאתן למרכז הבמה לראשונה.') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description) VALUES ('מסכת גאולה', 'מסכת-גאולה', 'תיאטרון תמונע', 60, 'מסכת גאולה הוא מופע מרגש המשלב דוקומנטרי ומוזיקה, העוסק בסיפור משפחתי מורכב ומאתגר את תפיסת המערכת החברתית.', 'מופע דוקומנטרי מוסיקלי המשלב סיפור אישי על משפחת אומנה עם היסטוריה משפחתית של שלושה דורות, המעלה שאלות על טובת הילד והחברה.') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description) VALUES ('עיגולים של שמחה', 'עיגולים-של-שמחה', 'תיאטרון תמונע', 50, 'עיגולים של שמחה הוא מופע קרקס מלא הומור ואופטימיות, המבטיח חוויית בידור בלתי נשכחת לכל המשפחה.', 'מופע קרקס מרהיב המציע רגעים מפתיעים ומרגשים, עם מסר חיובי על אופטימיות ושמחה, המיועד לכל המשפחה.') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description) VALUES ('פופלינדה בממלכת הדמיון', 'פופלינדה-בממלכת-הדמיון', 'תיאטרון תמונע', 50, 'פופלינדה בממלכת הדמיון הוא מופע קסום המשלב תיאטרון ומחול, המזמין את הילדים והמבוגרים לחקור את עולמות הדמיון וההרפתקה.', 'מופע תיאטרון-מחול המוביל את הקהל למסע דמיוני עם פופלינדה ורוברטו, המגלה את כוחות הדמיון והיצירה.') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description) VALUES ('קסמים בשחקים', 'קסמים-בשחקים', 'תיאטרון תמונע', 60, 'מופע קסמים וקרקס המשלב אשליות מרהיבות ולוליינות, המוביל את הקהל לעולם לא מוכר שבו ההגיוני והלא הגיוני מתערבבים.', 'ברוכים הבאים לעולם האשליות! עולם שבו ההגיוני נהיה לא הגיוני, והלא הגיוני הופך למציאות. רק קוסם עם רגליים על הקרקע ופייה מתעופפת, שלא ממש מסתדרים ביניהם, יצליחו לגרום לכם לא ללכת לגמרי לאיבוד. הצטרפו אלינו למסע קסום וקרקסי בין אשליות מופלאות ולוליינות מפעימה.') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description) VALUES ('שחף - עודד קוטלר', 'שחף-עודד-קוטלר', 'תיאטרון תמונע', 80, 'קומדיה דרמטית בהשראת אנטון צ''כוב, המשלבת כאוס משפחתי, מלחמות פנימיות ואהבות מסוכנות בצל מלחמה קשה.', 'משפחה, אמנים, שחקנים וסופרים מערבבים הלכות חיים, שאפתנות אמנותית, התאהבויות ובגידות בסיר לחץ אחד, וכל זאת בימי מלחמה קשה ואכזרית. גם מלחמתן של הדמויות זו בזו איננה מתנהלת בעצלתיים ובנימה משפחתית קרובה ונעימה. האנשים הללו מיואשים ופגועים, והאווירה מפוחדת ועצבנית.') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description) VALUES ('שלא יגמר לי', 'שלא-יגמר-לי', 'תיאטרון תמונע', 50, 'מופע פרפורמנס חדשני המשלב מחול וטקסט, חוקר את משמעות הזמן והמאבק להמשיך למרות האתגרים.', 'הגוף שלנו מדבר את הזמן. אנחנו נתלות בו, מותחות את הרגע, מחזיקות את הטריו – רק לא לעצור. זהו מופע פרפורמנס המשלב מחול, טקסט וביט, ועוסק ברלוונטיות שלנו, בהתעקשות ובמחיר שבבחירה להמשיך.') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description) VALUES ('שמואל', 'שמואל', 'תיאטרון תמונע', 70, 'קומדיה מופרעת על מסע בגיהנום, שבה יוני חייב לנצח בראפ-באטלים כדי להציל את חברו, תוך גילוי כוחות סליחה וחברות.', 'יוני מתעורר בגיהנום לאחר שהפסיד בקרב מול הדיכאון ושם קץ לחייו. שם הוא פוגש את אדולף היטלר, שעוזר לו במסעו חזרה לעולם החיים במטרה להציל את חברו שמואל. יוני חייב לנצח בראפ-באטלים בכל מדורי הגיהנום, לגלות את הכוח שבסליחה וחברות, ולהצית מחדש את האמונה בעצמו.') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description) VALUES ('According to Law', 'According-to-Law', 'תיאטרון תמונע', 60, 'מופע תיאטרון מחול סאטירי המאתגר את הקהל עם הפתעות בלתי צפויות, חקירות והומור על עולם התיאטרון.', 'מופע תיאטרון מחול סאטירי משעשע ומלא הפתעות על רקדנים, יוצרים, קהל וחוזים. זה ערב הבכורה והכל יכול להשתבש, אבל התיאטרון הוא מכונה משומנת וההצגה חייבת להימשך, במופע שכל הזמן הוא גם מה שהוא וגם דבר אחר לגמרי.') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description) VALUES ('HANNAH', 'HANNAH', 'תיאטרון תמונע', 90, 'דרמה מרגשת על חייה של חנה, נערה שחולמת על אהבה ובית, אך מוצאת את עצמה נאבקת על הישרדות בתקופה קשה.', 'זהו סיפורה של נערה בשם חנה, שחלמה להיות סופרת אך הפכה לצנחנית. היא ניסתה לשרוד בתוך ה"מטחנה" של המאה העשרים, סיפור על זיכרון, חלומות וחיפוש אחר האושר.') ON CONFLICT (slug) DO NOTHING;

-- ============================================================
-- 3. Insert ShowGenre join records
-- ============================================================
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'Can-you-beat-the-KGB' AND g.name = 'דרמה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'Can-you-beat-the-KGB' AND g.name = 'סאטירה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'אבהות' AND g.name = 'דרמה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'אבהות' AND g.name = 'מרגש' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'אדום' AND g.name = 'דרמה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'איך-לא-חשבתי-על-זה-קודם' AND g.name = 'קומדיה שחורה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'איך-לא-חשבתי-על-זה-קודם' AND g.name = 'מרגש' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'בילבי' AND g.name = 'ילדים' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'בילבי' AND g.name = 'מוזיקלי' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'דירה-לא-להשכיר' AND g.name = 'דרמה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'דירה-לא-להשכיר' AND g.name = 'מרגש' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'החולד-הקטן' AND g.name = 'ילדים' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'החולד-הקטן' AND g.name = 'מוזיקלי' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'הכל-נשאר-חי' AND g.name = 'דרמה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'הכל-נשאר-חי' AND g.name = 'מרגש' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'הכל-נשאר-חי' AND g.name = 'אינטימי' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'המורה' AND g.name = 'דרמה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'המורה' AND g.name = 'מרגש' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'הפצוע-הישראלי' AND g.name = 'קומדיה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'הפצוע-הישראלי' AND g.name = 'סאטירה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'יהושולה' AND g.name = 'דרמה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'יהושולה' AND g.name = 'מרגש' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'ימח-שמי' AND g.name = 'קומדיה שחורה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'כביסה-מלוכלכת-TAKE-3' AND g.name = 'דרמה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'לא-סוף-העולם' AND g.name = 'פנטזיה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'לא-סוף-העולם' AND g.name = 'רומנטי' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'לא-שקט' AND g.name = 'דרמה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'לא-שקט' AND g.name = 'מרגש' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'לאונרד' AND g.name = 'מרגש' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'מהפכניות' AND g.name = 'דרמה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'מהפכניות' AND g.name = 'סאטירה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'מסכת-גאולה' AND g.name = 'דרמה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'מסכת-גאולה' AND g.name = 'מרגש' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'עיגולים-של-שמחה' AND g.name = 'ילדים' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'עיגולים-של-שמחה' AND g.name = 'קומדיה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'פופלינדה-בממלכת-הדמיון' AND g.name = 'ילדים' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'פופלינדה-בממלכת-הדמיון' AND g.name = 'פנטזיה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'קסמים-בשחקים' AND g.name = 'ילדים' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'קסמים-בשחקים' AND g.name = 'פנטזיה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'שחף-עודד-קוטלר' AND g.name = 'דרמה קומית' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'שלא-יגמר-לי' AND g.name = 'דרמה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'שמואל' AND g.name = 'קומדיה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'שמואל' AND g.name = 'דרמה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'According-to-Law' AND g.name = 'סאטירה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'According-to-Law' AND g.name = 'קומדיה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'HANNAH' AND g.name = 'דרמה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'HANNAH' AND g.name = 'מרגש' ON CONFLICT DO NOTHING;

-- ============================================================
-- 4. Reset sequences
-- ============================================================
SELECT setval(pg_get_serial_sequence('"Show"', 'id'), (SELECT MAX(id) FROM "Show"));
SELECT setval(pg_get_serial_sequence('"Genre"', 'id'), (SELECT MAX(id) FROM "Genre"));
