export interface ActorInfo {
  /** URL slug (Hebrew, matching image filename) */
  slug: string;
  /** Hebrew display name */
  name: string;
  /** Image path in /public/actors/ */
  image: string;
}

export const ACTORS: ActorInfo[] = [
  { slug: "אביגיל-הררי", name: "אביגיל הררי", image: "/actors/אביגיל-הררי.webp" },
  { slug: "אבי-קושניר", name: "אבי קושניר", image: "/actors/אבי-קושניר.webp" },
  { slug: "אודיה-קורן", name: "אודיה קורן", image: "/actors/אודיה-קורן.webp" },
  { slug: "אולה-שור-סלקטר", name: "אולה שור סלקטר", image: "/actors/אולה-שור-סלקטר.webp" },
  { slug: "אוראל-צברי", name: "אוראל צברי", image: "/actors/אוראל-צברי.webp" },
  { slug: "אלון-סנדלר", name: "אלון סנדלר", image: "/actors/אלון-סנדלר.webp" },
  { slug: "אלי-גורנשטיין", name: "אלי גורנשטיין", image: "/actors/אלי-גורנשטיין.webp" },
  { slug: "אלכס-קרול", name: "אלכס קרול", image: "/actors/אלכס-קרול.webp" },
  { slug: "איה-גרניט-שבא", name: "איה גרניט שבא", image: "/actors/איה-גרניט-שבא.webp" },
  { slug: "אילי-עלמני", name: "אילי עלמני", image: "/actors/אילי-עלמני.webp" },
  { slug: "אלון-אופיר", name: "אלון אופיר", image: "/actors/אלון-אופיר.webp" },
  { slug: "אלעד-אטרקצ׳י", name: "אלעד אטרקצ׳י", image: "/actors/אלעד-אטרקצ׳י.webp" },
  { slug: "גילה-אלמגור", name: "גילה אלמגור", image: "/actors/גילה-אלמגור.webp" },
  { slug: "גילת-אנקורי", name: "גילת אנקורי", image: "/actors/גילת-אנקורי.webp" },
  { slug: "גלית-גיאת", name: "גלית גיאת", image: "/actors/גלית-גיאת.webp" },
  { slug: "גלעד-מרחבי", name: "גלעד מרחבי", image: "/actors/גלעד-מרחבי.webp" },
  { slug: "ג׳וי-ריגר", name: "ג׳וי ריגר", image: "/actors/ג׳וי-ריגר.webp" },
  { slug: "דביר-בנדק", name: "דביר בנדק", image: "/actors/דביר-בנדק.webp" },
  { slug: "דור-אלמקייס", name: "דור אלמקייס", image: "/actors/דור-אלמקייס.webp" },
  { slug: "דור-הררי", name: "דור הררי", image: "/actors/דור-הררי.webp" },
  { slug: "דניאל-גל", name: "דניאל גל", image: "/actors/דניאל-גל.webp" },
  { slug: "דניאל-סטיופין", name: "דניאל סטיופין", image: "/actors/דניאל-סטיופין.webp" },
  { slug: "דרור-קרן", name: "דרור קרן", image: "/actors/דרור-קרן.webp" },
  { slug: "הגר-אנגל", name: "הגר אנגל", image: "/actors/הגר-אנגל.webp" },
  { slug: "חני-פירסטנברג", name: "חני פירסטנברג", image: "/actors/חני-פירסטנברג.webp" },
  { slug: "חן-גרטי", name: "חן גרטי", image: "/actors/חן-גרטי.webp" },
  { slug: "חנה-לסלאו", name: "חנה לסלאו", image: "/actors/חנה-לסלאו.webp" },
  { slug: "חני-נחמיאס", name: "חני נחמיאס", image: "/actors/חני-נחמיאס.webp" },
  { slug: "טל-גרושקה", name: "טל גרושקה", image: "/actors/טל-גרושקה.webp" },
  { slug: "טל-מוסרי", name: "טל מוסרי", image: "/actors/טל-מוסרי.webp" },
  { slug: "טלי-אורן", name: "טלי אורן", image: "/actors/טלי-אורן.webp" },
  { slug: "יחזקאל-לזרוב", name: "יחזקאל לזרוב", image: "/actors/יחזקאל-לזרוב.webp" },
  { slug: "יונה-אליאן-קשת", name: "יונה אליאן קשת", image: "/actors/יונה-אליאן-קשת.webp" },
  { slug: "יורם-טולדנו", name: "יורם טולדנו", image: "/actors/יורם-טולדנו.webp" },
  { slug: "יניב-סויסה", name: "יניב סויסה", image: "/actors/יניב-סויסה.webp" },
  { slug: "יעל-לבנטל", name: "יעל לבנטל", image: "/actors/יעל-לבנטל.webp" },
  { slug: "יפתח-קליין", name: "יפתח קליין", image: "/actors/יפתח-קליין.webp" },
  { slug: "כינרת-לימוני", name: "כינרת לימוני", image: "/actors/כינרת-לימוני.webp" },
  { slug: "כרמל-בין", name: "כרמל בין", image: "/actors/כרמל-בין.webp" },
  { slug: "לי-בירן", name: "לי בירן", image: "/actors/לי-בירן.webp" },
  { slug: "ליא-קניג", name: "ליא קניג", image: "/actors/ליא-קניג.webp" },
  { slug: "ליאור-אשכנזי", name: "ליאור אשכנזי", image: "/actors/ליאור-אשכנזי.webp" },
  { slug: "ליהי-טולדנו", name: "ליהי טולדנו", image: "/actors/ליהי-טולדנו.webp" },
  { slug: "לימור-גולדשטיין", name: "לימור גולדשטיין", image: "/actors/לימור-גולדשטיין.webp" },
  { slug: "לינוי-כהן", name: "לינוי כהן", image: "/actors/לינוי-כהן.webp" },
  { slug: "לאורה-ריבלין", name: "לאורה ריבלין", image: "/actors/לאורה-ריבלין.webp" },
  { slug: "מאיה-לבני", name: "מאיה לבני", image: "/actors/מאיה-לבני.webp" },
  { slug: "מאיה-מעוז", name: "מאיה מעוז", image: "/actors/מאיה-מעוז.webp" },
  { slug: "מגי-אזרזר", name: "מגי אזרזר", image: "/actors/מגי-אזרזר.webp" },
  { slug: "מיה-לנדסמן", name: "מיה לנדסמן", image: "/actors/מיה-לנדסמן.webp" },
  { slug: "מיכאל-בן-דוד", name: "מיכאל בן דוד", image: "/actors/מיכאל-בן-דוד.webp" },
  { slug: "מיקי-קם", name: "מיקי קם", image: "/actors/מיקי-קם.webp" },
  { slug: "מולי-שולמן", name: "מולי שולמן", image: "/actors/מולי-שולמן.webp" },
  { slug: "מיקה-צור", name: "מיקה צור", image: "/actors/מיקה-צור.webp" },
  { slug: "מעיין-תורג׳מן", name: "מעיין תורג׳מן", image: "/actors/מעיין-תורג׳מן.webp" },
  { slug: "מרים-זוהר", name: "מרים זוהר", image: "/actors/מרים-זוהר.webp" },
  { slug: "משי-קלינשטיין", name: "משי קלינשטיין", image: "/actors/משי-קלינשטיין.webp" },
  { slug: "מתן-און-ימי", name: "מתן און ימי", image: "/actors/מתן-און-ימי.webp" },
  { slug: "נדב-אסולין", name: "נדב אסולין", image: "/actors/נדב-אסולין.webp" },
  { slug: "נדב-נייטס", name: "נדב נייטס", image: "/actors/נדב-נייטס.webp" },
  { slug: "נורמן-עיסא", name: "נורמן עיסא", image: "/actors/נורמן-עיסא.webp" },
  { slug: "נמרוד-גרינבוים", name: "נמרוד גרינבוים", image: "/actors/נמרוד-גרינבוים.webp" },
  { slug: "נטע-גרטי", name: "נטע גרטי", image: "/actors/נטע-גרטי.webp" },
  { slug: "נועם-קלינשטיין", name: "נועם קלינשטיין", image: "/actors/נועם-קלינשטיין.webp" },
  { slug: "נעמה-שטרית", name: "נעמה שטרית", image: "/actors/נעמה-שטרית.webp" },
  { slug: "נעמי-הררי", name: "נעמי הררי", image: "/actors/נעמי-הררי.webp" },
  { slug: "נתן-דטנר", name: "נתן דטנר", image: "/actors/נתן-דטנר.webp" },
  { slug: "סנדרה-שדה", name: "סנדרה שדה", image: "/actors/סנדרה-שדה.webp" },
  { slug: "עדי-כהן", name: "עדי כהן", image: "/actors/עדי-כהן.webp" },
  { slug: "עידו-רוזנברג", name: "עידו רוזנברג", image: "/actors/עידו-רוזנברג.webp" },
  { slug: "עידן-אלתרמן", name: "עידן אלתרמן", image: "/actors/עידן-אלתרמן.webp" },
  { slug: "עירית-ענבי", name: "עירית ענבי", image: "/actors/עירית-ענבי.webp" },
  { slug: "עמוס-תמם", name: "עמוס תמם", image: "/actors/עמוס-תמם.webp" },
  { slug: "עמי-ויינברג", name: "עמי ויינברג", image: "/actors/עמי-ויינברג.webp" },
  { slug: "ענת-וקסמן", name: "ענת וקסמן", image: "/actors/ענת-וקסמן.webp" },
  { slug: "עופרי-ביטרמן", name: "עופרי ביטרמן", image: "/actors/עופרי-ביטרמן.webp" },
  { slug: "צביקה-הדר", name: "צביקה הדר", image: "/actors/צביקה-הדר.webp" },
  { slug: "צחי-הלוי", name: "צחי הלוי", image: "/actors/צחי-הלוי.webp" },
  { slug: "ציפי-שביט", name: "ציפי שביט", image: "/actors/ציפי-שביט.webp" },
  { slug: "פיני-קדרון", name: "פיני קדרון", image: "/actors/פיני-קדרון.webp" },
  { slug: "פנינה-ברט-צדקה", name: "פנינה ברט צדקה", image: "/actors/פנינה-ברט-צדקה.webp" },
  { slug: "קרן-מור", name: "קרן מור", image: "/actors/קרן-מור.webp" },
  { slug: "קרן-מור-מישורי", name: "קרן מור מישורי", image: "/actors/קרן-מור-מישורי.webp" },
  { slug: "רביב-כנר", name: "רביב כנר", image: "/actors/רביב-כנר.webp" },
  { slug: "רוני-דלומי", name: "רוני דלומי", image: "/actors/רוני-דלומי.webp" },
  { slug: "רבקה-מיכאלי", name: "רבקה מיכאלי", image: "/actors/רבקה-מיכאלי.webp" },
  { slug: "רויטל-זלצמן", name: "רויטל זלצמן", image: "/actors/רויטל-זלצמן.webp" },
  { slug: "רמי-ברוך", name: "רמי ברוך", image: "/actors/רמי-ברוך.webp" },
  { slug: "רן-דנקר", name: "רן דנקר", image: "/actors/רן-דנקר.webp" },
  { slug: "רפאל-עבאס", name: "רפאל עבאס", image: "/actors/רפאל-עבאס.webp" },
  { slug: "ריקי-בליך", name: "ריקי בליך", image: "/actors/ריקי-בליך.webp" },
  { slug: "תום-אבני", name: "תום אבני", image: "/actors/תום-אבני.webp" },
  { slug: "תום-חודורוב", name: "תום חודורוב", image: "/actors/תום-חודורוב.webp" },
  { slug: "תומר-מחלוף", name: "תומר מחלוף", image: "/actors/תומר-מחלוף.webp" },
  { slug: "תם-גל", name: "תם גל", image: "/actors/תם-גל.webp" },
];

/** Map from URL slug → actor info */
export const ACTOR_BY_SLUG = new Map(ACTORS.map((a) => [a.slug, a]));

/** Map from Hebrew display name → actor info */
export const ACTOR_BY_NAME = new Map(ACTORS.map((a) => [a.name, a]));
