-- Migration: Add new all_theatres shows
-- Generated on 2026-04-18T21:32:26.132Z
-- This migration is idempotent (uses ON CONFLICT DO NOTHING).

-- ============================================================
-- 1. Insert Genres
-- ============================================================
INSERT INTO "Genre" (name) VALUES ('דוקומנטרי') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Genre" (name) VALUES ('דרמה') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Genre" (name) VALUES ('דרמה קומית') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Genre" (name) VALUES ('ילדים') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Genre" (name) VALUES ('ישראלי') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Genre" (name) VALUES ('מוזיקלי') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Genre" (name) VALUES ('מחזמר') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Genre" (name) VALUES ('מרגש') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Genre" (name) VALUES ('סאטירה') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Genre" (name) VALUES ('קומדיה') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Genre" (name) VALUES ('קומדיה שחורה') ON CONFLICT (name) DO NOTHING;

-- ============================================================
-- 2. Insert Shows
-- ============================================================
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description, "cast") VALUES ('אדום', 'אדום', 'הפקות עצמאיות', 70, 'דרמה עוצמתית על המאבק בין האמנות לאקט המסחרי, המתרחשת בין האמן מארק רות''קו לאסיסטנט הצעיר שלו, המאתגרת את ערכיו האומנותיים.', 'דרמה לחיים ומוות על אומנות חברות ופער הדורות. הצייר מארק רות''קו מתמודד עם האקט המסחרי של יצירת ציורים למסעדה, בעודו מתעמת עם ערכיו האומנותיים ועם האסיסטנט הצעיר שלו. המחזה מציע דיאלוגים טעונים ורגעים של פגיעות רגשית, ומשרטט את דיוקן האמן הבלתי מתפשר.', 'אוהד שחר, יחיעם ברקו') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description, "cast") VALUES ('איך לא חשבתי על זה קודם', 'איך-לא-חשבתי-על-זה-קודם', 'הפקות עצמאיות', 60, 'קומדיה שחורה ורגישה על קשיש המגלה סוד מעברו, המאתגר את תפיסתו על החיים והבדידות, ומזמין את הצופים לחשוב על משמעות הקיום.', 'תומס, קשיש מר נפש, נפגש עם דמויות שונות שמביאות אותו להתמודד עם החיים, המוות והבדידות. המפגשים חושפים סוד מעברם המשותף ומובילים אותו להבנה חדשה על הבחירות בחייו. מדובר ביצירה קומית אירונית המשלבת מחשבות על זיקנה ובדידות.', 'אורי אברהמי, אלי דנקר/אייל נחמיאס, שאול עזר') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description, "cast") VALUES ('אם16 - תמונת ניצחון!', 'אם16-תמונת-ניצחון!', 'הפקות עצמאיות', 50, 'פרפורמנס עוצמתי המאתגר את המיתוס של החייל ההירואי בישראל, ומעורר שאלות על מחיר הלחימה וההיסטוריה של החברה הישראלית.', 'ההצגה בוחנת את דמות החייל בישראל של 2022, דרך פרפורמנס אינטנסיבי המעלה שאלות על המחיר של הלחימה וההיסטוריה. היוצרים מתמודדים עם ההתרסקות ההיסטורית של דמות החייל ההירואי ומבקרים את התפיסות החברתיות המובילות לשליחת בנים ובנות לשדות הקרב.', 'אילון פרבר, איסק צ''וקרון, אליק ניב, סהר עזימי ') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description, "cast") VALUES ('אקספוז''ר', 'אקספוז׳ר', 'הפקות עצמאיות', 55, 'דרמה מטלטלת על המחיר של חשיפת סודות אישיים, המאתגרת את הדמויות והקהל להתמודד עם מה שלא מדברים עליו.', 'הבמאי נדב אמיר מתמודד עם הסודות שלו כאשר הוא מלהק שחקנית צעירה למחזה חדש. המחזה עוסק במאבק הפנימי של דמויותיו לחשוף את עצמם, והקונפליקטים שמתרקמים במשפחה ובעבודה בעקבות החשיפה.', 'נעם ברמט, אלירן כספי') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description, "cast") VALUES ('את מדברת. אני מדברת', 'את-מדברת.-אני-מדברת', 'הפקות עצמאיות', 70, 'מונודרמה מרתקת המשלבת בין עבר להווה, ומאתגרת את הקהל לשאול שאלות על זהות, חיים וההיסטוריה של הנשים.', 'שתי נשים, אחת מהעבר ואחת מההווה, מתמודדות עם שאלות על החיים וההיסטוריה. המונודרמה עוסקת בהבנה ובחקר של זהותן, ויוצרת חיבור בין העבר להווה, תוך כדי חקירה של משמעות הקיום.', 'ריקי חיות') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description, "cast") VALUES ('בית בעזה', 'בית-בעזה', 'הפקות עצמאיות', 60, 'פרפורמנס ייחודי המשלב חפצים יומיומיים כדי לחקור את המצב במלחמה, ומציע מבט מעמיק על השפעתה על החיים והזהות.', 'פרפורמנס חפצים המתאר את הימים הראשונים במלחמה, כאשר המפקד מסביר לצוות את המצב באמצעות חפצים יומיומיים. דניאל אנגל מתמודד עם המורכבות של המלחמה והחיים דרך חפצים המייצגים את השפעתה.', 'דניאל אנגל') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description, "cast") VALUES ('המדריך לגידול המת', 'המדריך-לגידול-המת', 'הפקות עצמאיות', 60, 'מופע מרגש המעמיק בקשרים עם המתים, ומזמין את הקהל לחשוב על השפעתם על החיים והזיכרון.', 'ההצגה עוסקת בקשרים עם המתים, ובמהלך המופע משפחת לופו חוקרת את מערכות היחסים שלה עם הנפטרים. היא מתמודדת עם השאלות הלא נוחות על מה קורה לאחר המוות ואיך ממשיכים לחיות עם הזיכרונות.', 'טל שדה, ליאור לב/מאשה שמוליאן, עירית נתן בנדק, רינה פדווה') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description, "cast") VALUES ('הפצוע הישראלי', 'הפצוע-הישראלי', 'הפקות עצמאיות', 70, 'קומדיה סאטירית המגוללת את סיפורו של פצוע מסתורי בבית חולים, תוך חקירת טראומות עבר והיחסים בין אמנות לפוליטיקה.', 'פצוע מסתורי שוכב בחדר בבית החולים. עם כל מבקר שמגיע אליו, הולכת ומסתבכת התעלומה סביב זהותו האמיתית ונסיבות הגעתו למחלקה. מחזה מקורי שבוחן את הדרכים בהן אמנות, פוליטיקה ורוחניות יכולות לעזור לנו להתמודד עם טראומות עבר.', 'מעין בלום, שמעון מימרן/יגאל זקס, ליז רביאן, אורלי טובלי, ויקטור סבג') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description, "cast") VALUES ('לא שקט', 'לא-שקט', 'הפקות עצמאיות', 60, 'דרמה נוגעת ללב המשלבת זיכרון ודחק, בה גבר מתמודד עם חוויותיו הקשות בעקבות הפסקת הריון.', 'לפעמים אנחנו רוצים לזכור אבל המוח שלנו מתעקש להפך. אמרנו לו פעם לשכוח, הוא הקשיב ועכשיו חלקים שלמים לא זמינים לנו.
אני הדחקתי את כל מה שקרה במהלך, מסביב ואחרי הפסקת ההריון של אישתי ועכשיו עולות לי מלא שאלות.
אז בואו נדבר על זה כי לבד אני לא מצליח להזכר.

הצגת יחיד מאת ובביצוע אבי גולומב על חוויית הגבר בהפסקת הריון של אשתו תוך ניסיון להיזכר באירועים שהדחיק מאותה תקופה.', 'אבי גולומב') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description, "cast") VALUES ('מסכת גאולה', 'מסכת-גאולה', 'הפקות עצמאיות', 60, 'מופע דוקומנטרי מוסיקלי המשלב סיפור אישי עם היסטוריה משפחתית, המאתגר את המערכת והמדינה ביחסיהם עם ילדים חסרי מעמד.', 'מופע דוקומנטרי מוסיקלי המתאר את סיפורם של בני זוג שהיו משפחת אומנה לילדה חסרת מעמד, עד שהוחזרה לאמה הביולוגית. המופע עוסק במערכת היחסים בין טובת הילד, החברה והלאום.', NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description, "cast") VALUES ('שייקספיר בחווה הסינית', 'שייקספיר-בחווה-הסינית', 'הפקות עצמאיות', 60, 'קומדיה טראגית המתרחשת במועדון לנפגעי הלם קרב, שם מתמודדים חיילים עם זיכרונות מלחמה וכאב אישי.', 'יודקה פלס, שחקן שייקספירי מפורסם, יושב בבית בגלל המגפה. בתו פזית מנסה למצוא לו מקום להופיע, עד שהיא מגיעה למועדון לנפגעי הלם קרב ממלחמת יום כיפור.', 'דורון צפריר, יהודה לזרוביץ,  ניר ביקלס, נופר לוינגר') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description, "cast") VALUES ('HANNAH', 'HANNAH', 'הפקות עצמאיות', 90, 'דרמה מרגשת על נערה שחלמה להיות סופרת, אך מצאה את עצמה במציאות קשה של מלחמה וזיכרון.', 'סיפורה של נערה בשם חנה, שהפכה לצנחנית במקום להיות סופרת. היא חיה בין חלומות למציאות קשה, ונאבקת לשרוד בתוך המאה העשרים.', 'סופה צ‘ודנובסקי, יורי קזנצב, גריגורי קצנלסון, מריה מקייב/יבגניה נתנוב') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description, "cast") VALUES ('סודות בוערים', 'סודות-בוערים', 'תיאטרון הסימטה', 60, 'דרמה משפחתית מרגשת שבה דנה מציבה אולטימטום לאחיה, חושפת סודות ישנים ומובילה למסע אל העבר עם סוף מפתיע.', 'דנה חוזרת לארץ אחרי שנים ומציבה לאחיה למחצה אולטימטום שמטלטל את חייו. ההתנגדות שלו חושפת סודות ושקרים ישנים. מה שמתחיל כמחלוקת משפחתית הופך למסע אל העבר – עם סוף בלתי צפוי.', 'אלון לשם, ענת מידן') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description, "cast") VALUES ('אור', 'אור', 'תיאטרון הליצנות דוואי', 60, 'אור היא הצגת ליצנות מרגשת המשלבת מסרים של תקווה ואופטימיות, בהשראת המלחמה באוקראינה.', 'ההצגה עוסקת במלחמה באוקראינה ובמאבק נגד החושך בעזרת אור וצחוק. היא מציעה מסר של תקווה ואופטימיות, ומדברת על המחשבות הטובות שניתן להפעיל כדי להתמודד עם הקשיים.', NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description, "cast") VALUES ('אחים סמארטפון', 'אחים-סמארטפון', 'תיאטרון הליצנות דוואי', 50, 'אחים סמארטפון היא קומדיה משפחתית מלאת סלאפסטיק וחפצים, המציעה מסע משעשע על חיפוש משמעות בעידן הדיגיטלי.', 'ההצגה עוקבת אחרי האחים סמארטפון שחוגגים את רכישת המכשיר החדש, אך כאשר הוא נשבר, הם יוצאים למסע חיפוש אחריו, תוך התמודדות עם החיים והקשרים ביניהם.', 'ויטלי אזרין') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description, "cast") VALUES ('אפצ׳י', 'אפצ׳י', 'תיאטרון הליצנות דוואי', 50, 'אפצ׳י היא הצגת תיאטרון חזותי-פיזי ללא מילים, המיועדת לילדים ומציעה מסע משעשע של התמודדות עם אתגרים.', 'ההצגה מתארת את הליצן שמנסה לדוג דג גדול אך נתקל בקשיים בעקבות מזג האוויר. הוא מתמודד עם רחמים עצמיים וממציא תרופת פלא כדי להתגבר על הקשיים.', 'לושה גבריאלוב') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description, "cast") VALUES ('הדבר העגול הזה', 'הדבר-העגול-הזה', 'תיאטרון הליצנות דוואי', 50, 'הדבר העגול הזה הוא מופע ליצנות משפחתי מלא הרפתקאות, המשלב קומדיה ודרמה בחיפוש אחר השמש.', 'ההצגה מגוללת את סיפורם של שני ליצנים המפילים בטעות את השמש לים, ומצטרפים להרפתקה בחיפוש אחר השמש, תוך חוויות ורגשות משתנים.', NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description, "cast") VALUES ('המזיענים', 'המזיענים', 'תיאטרון הליצנות דוואי', 40, 'המזיענים הוא מופע קומי ודינמי המשלב ליצנות, סלאפסטיק ופעילויות אינטראקטיביות, המיועד לכל המשפחה.', 'המופע מציע חגיגה תיאטרלית בשיתוף הקהל עם ארבעה ליצנים מהאייטיז, המשלבים כושר גופני, הומור וצבעוניות, תוך כדי פעילויות יצירה בחצר.', NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description, "cast") VALUES ('סבתא פרידה', 'סבתא-פרידה', 'תיאטרון הליצנות דוואי', 45, 'סבתא פרידה היא קומדיה מפתיעה ומרגשת על בדידות ושמחה, המיועדת לכל המשפחה.', 'ההצגה עוקבת אחרי סבתא פרידה הבודדה, שמוצאת את השמחה וההרפתקאות בחיי היומיום שלה, תוך שימוש בהומור והפתעות.', NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description, "cast") VALUES ('עומאר טריו', 'עומאר-טריו', 'תיאטרון הליצנות דוואי', 60, 'עומאר טריו הוא מופע מוזיקלי ייחודי המשלב קונצרט עם חקירות פילוסופיות, המציע חוויה אמנותית מרגשת.', 'ההצגה מציעה מסע מוזיקלי מלנכולי בהשראת סיפורו של סמואל בקט, עם שירים מקוריים ומוזיקה מגוונת, תוך חקירת זהות והומור.', NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description, "cast") VALUES ('ONE THING SHOW', 'ONE-THING-SHOW', 'תיאטרון הליצנות דוואי', 50, 'ההצגה ללא מילים לוקחת את הצופים למסע פואטי ואבסורדי בעזרת חפץ אחד, המשלב הומור ויצירתיות יוצאת דופן.', 'על הקו שבין יש ואין ובין דרמה לקומדיה נמצאת ה״הצגה של חפץ אחד״ – הצגת תיאטרון ללא מילים וללא תפאורה, מופע פואטי על משמעות החיים בעזרת חפץ חסר משמעות. מסע מכשף אל מקור היצירתיות וההמצאה, שתצאו ממנו מלאי השראה שואב את הצופה לתוך עולם לירי, רווי בהומור אבסורדי מבעד לגרוטסקה הליצנית. הווירטואוזיות התנועתית והצחוק, מבצבצות תובנות על העולם ועל האדם החי בתוכו.', NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description, "cast") VALUES ('UNDER CONSTRUCTION', 'UNDER-CONSTRUCTION', 'תיאטרון הליצנות דוואי', 80, 'שלושה רווקים מנסים להרתיח קומקום בדירה מתפרקת, ויוצרים מופע פיזי מלא הומור מטורף ללא מילים שמספק חוויה אבסורדית ומרתקת.', 'מופע תיאטרון פיזי ללא מילים שבו שלושה רווקים מתעוררים בבוקר בדירתם הצפוצה והמתפרקת ומנסים להרתיח קומקום. התוצאה – 80 דקות של הומור מטורף שסוחפות את הצופה לעולם אבסורדי, בדיוני, ואמיתי עד כדי דגדוג.', 'לושה גבריאלוב, פיודור מקרוב, ויטלי אזרין') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description, "cast") VALUES ('וויסקי על הבוקר', 'וויסקי-על-הבוקר', 'הפקות עצמאיות', 75, 'קומדיה נשית משעשעת על שלוש שותפות לדירה בשנות ה-90, המתמודדות עם בעיות חיים ואלכוהול בבוקר אחד בלתי נשכח.', 'בבוקר יפה באמריקה של שנות ה-90, שלוש שותפות מחליטות לשתות וויסקי לארוחת בוקר. האלכוהול מתחיל לזרום, והשותפות לדירה נאלצות להתמודד אחת עם השניה, ועם בעיות כמו הריון לא רצוי, מטרידן בעבודה, שאלות על דת ועל גיל 30. ''וויסקי על הבוקר'' היא קומדיה אנושית ונשית המספרת את סיפורו של דור שלם של נשים אבודות בתחילת שנות ה-30 לחייהן.', 'תרזה ריבק, שיר ארביב, מאי באום אוונס, מור ברגמן, שרון ליבובסקי, אהרון בנפשי') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description, "cast") VALUES ('ימים רגילים', 'ימים-רגילים', 'הפקות עצמאיות', 90, 'מחזמר מרגש על ארבעה ניו-יורקרים המחפשים אהבה והגשמה, כאשר חייהם מצטלבים ביום רגיל אחד שלא ישכחו.', 'ארבעה ניו-יורקרים: וורן - אמן מתוסכל, דב - סטודנטית, ג''ייסון וקלייר - זוג טרי, מתכננים את הצעד הבא בחיים. בין חיפוש מונית לחיפוש עבודה הם מחפשים אושר, הגשמה ואהבה. דרך פגישות מקריות, שני הסיפורים שלהם מצטלבים בצורה מרגשת ובלתי צפויה ביום רגיל אחד, שלעולם לא ישכחו. המחזמר ''ימים רגילים'' מאיר בצורה יוצאת דופן את הדברים הפשוטים שבחיים ואת הקשר המיוחד בין בני אדם.', 'עילי שמרץ, אהרון בנפשי, מאי באום אוונס, עילי שמרץ, יעל שמילה \ יעל שיזף, עדן ביטון / אופק ששון , אריאל דימנט \ שיר בודק , עדי שרון \ עדי שור , אהרון בנפשי \ כפיר מדניצקי') ON CONFLICT (slug) DO NOTHING;

-- ============================================================
-- 3. Insert ShowGenre join records
-- ============================================================
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'אדום' AND g.name = 'דרמה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'איך-לא-חשבתי-על-זה-קודם' AND g.name = 'קומדיה שחורה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'איך-לא-חשבתי-על-זה-קודם' AND g.name = 'מרגש' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'אם16-תמונת-ניצחון!' AND g.name = 'ישראלי' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'אם16-תמונת-ניצחון!' AND g.name = 'דרמה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'אקספוז׳ר' AND g.name = 'דרמה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'את-מדברת.-אני-מדברת' AND g.name = 'דרמה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'בית-בעזה' AND g.name = 'דרמה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'המדריך-לגידול-המת' AND g.name = 'מרגש' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'הפצוע-הישראלי' AND g.name = 'קומדיה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'הפצוע-הישראלי' AND g.name = 'סאטירה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'לא-שקט' AND g.name = 'דרמה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'לא-שקט' AND g.name = 'מרגש' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'מסכת-גאולה' AND g.name = 'מוזיקלי' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'מסכת-גאולה' AND g.name = 'ישראלי' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'מסכת-גאולה' AND g.name = 'דוקומנטרי' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'שייקספיר-בחווה-הסינית' AND g.name = 'קומדיה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'שייקספיר-בחווה-הסינית' AND g.name = 'דרמה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'HANNAH' AND g.name = 'דרמה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'HANNAH' AND g.name = 'מרגש' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'סודות-בוערים' AND g.name = 'דרמה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'סודות-בוערים' AND g.name = 'מרגש' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'אור' AND g.name = 'מרגש' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'אור' AND g.name = 'קומדיה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'אחים-סמארטפון' AND g.name = 'קומדיה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'אחים-סמארטפון' AND g.name = 'ישראלי' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'אפצ׳י' AND g.name = 'ילדים' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'אפצ׳י' AND g.name = 'קומדיה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'הדבר-העגול-הזה' AND g.name = 'קומדיה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'הדבר-העגול-הזה' AND g.name = 'דרמה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'המזיענים' AND g.name = 'קומדיה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'המזיענים' AND g.name = 'ילדים' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'סבתא-פרידה' AND g.name = 'מרגש' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'סבתא-פרידה' AND g.name = 'קומדיה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'עומאר-טריו' AND g.name = 'מוזיקלי' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'עומאר-טריו' AND g.name = 'מרגש' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'ONE-THING-SHOW' AND g.name = 'דרמה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'ONE-THING-SHOW' AND g.name = 'קומדיה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'UNDER-CONSTRUCTION' AND g.name = 'קומדיה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'UNDER-CONSTRUCTION' AND g.name = 'דרמה קומית' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'וויסקי-על-הבוקר' AND g.name = 'קומדיה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'וויסקי-על-הבוקר' AND g.name = 'דרמה קומית' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'ימים-רגילים' AND g.name = 'מחזמר' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'ימים-רגילים' AND g.name = 'מרגש' ON CONFLICT DO NOTHING;

-- ============================================================
-- 4. Reset sequences
-- ============================================================
SELECT setval(pg_get_serial_sequence('"Show"', 'id'), (SELECT MAX(id) FROM "Show"));
SELECT setval(pg_get_serial_sequence('"Genre"', 'id'), (SELECT MAX(id) FROM "Genre"));
