-- Migration: Add new all_theatres shows
-- Generated on 2026-04-07T22:27:44.010Z
-- This migration is idempotent (uses ON CONFLICT DO NOTHING).

-- ============================================================
-- 1. Insert Genres
-- ============================================================
INSERT INTO "Genre" (name) VALUES ('דרמה') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Genre" (name) VALUES ('דרמה קומית') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Genre" (name) VALUES ('מוזיקלי') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Genre" (name) VALUES ('מחזמר') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Genre" (name) VALUES ('מרגש') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Genre" (name) VALUES ('סאטירה') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Genre" (name) VALUES ('קומדיה') ON CONFLICT (name) DO NOTHING;
INSERT INTO "Genre" (name) VALUES ('קומדיה שחורה') ON CONFLICT (name) DO NOTHING;

-- ============================================================
-- 2. Insert Shows
-- ============================================================
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description, "cast") VALUES ('& איב', 'איב', 'הפקות עצמאיות', 60, 'קומדיה מוזיקלית סוחפת על אהבה בלתי אפשרית בין אדם לבינה מלאכותית, המאתגרת את הגבולות בין אנושיות לטכנולוגיה.', 'האם אפשר לתכנת אהבת אמת? תומר מתחתן עם בינה מלאכותית שהוא יצר, אך בדרך יש מכשולים שמאתגרים את אהבתם. קומדיה מוזיקלית שמאתגרת את הגבולות בין אנושיות לטכנולוגיה.', 'איתי זיו, יעל לבקוביץ׳-ברזילי, איתמר מנדלסון, נועם אמזלג, תובל שפיר, לאה אלון מגן / מיכל גומפרט, יעל לבקוביץ׳ -ברזילי, איתמר מנדלסון, עדי זינגר, איתמר שרון, רוני שושן, חן ווינר-שוסטק, רפאל שריה-צרפתי / ים בן דוד, נועם אמזלג, איתי זיו') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description, "cast") VALUES ('דיברת אלי?', 'דיברת-אלי', 'הפקות עצמאיות', 75, 'דרמה קומית מפתיעה על אם חד הורית שמקבלת שליחות מפתיעה ומצטרפת למאבק להציל משהו או מישהו, תוך כדי התמודדות עם חייה האישיים.', 'בדרמה קומית מפתיעה, ריקה, אם חד הורית, מקבלת שליחות מפתיעה ומצטרפת לשף מתוסכל ובן מתבגר, במטרה להציל משהו או מישהו.', 'בצלאל בורוכוב, יובל אנדבלד , נתנאלה תירוש, עוז סלוק, ענת צור, אודי בן משה, הרב יוסי פרומן, בני אלדר') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description, "cast") VALUES ('הולכים לעולמם', 'הולכים-לעולמם', 'הפקות עצמאיות', 75, 'קומדיה בירוקרטית על החיים והמוות, המתרחשת בעולם החוות ומציעה חווית קליטה ייחודית למשתתפים.', 'קומדיה בירוקרטית על המוות, המתרחשת בעולם החוות, המקשר בין החיים והמוות. תהליך בירוקרטי קצר ממתין למשתתפים, עם שאלות על מה שלא הספיקו.', 'דניאל עובדיה ונתנאל רפפורט, עלי קפלן וילדמן, ענבל מזרחי- אספרנסה, דורין דר, עמית לויט, דניאל עובדיה, בהט קלצ''י, נתנאל רפפורט') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description, "cast") VALUES ('הלהצ"ר', 'הלהצ-ר', 'הפקות עצמאיות', 100, 'מחזמר קליל וביקורתי על מאבק בין חוקי הצבא לרצונות מוזיקליים, עם סיפור אהבה אסור בין לוחמים צעירים.', 'מחזמר קליל וביקורתי על מאבק בין חוקי הצבא לרצונות מוזיקליים של צעירים. סיפור על יחידת חילוץ מוסווית כלהקה צבאית, עם אהבות אסורות.', 'ודים קשרסקי, טל עמר, יאל רודיך, מאי שטיימן, גל מגן, קורל אנבל לוקץ'', הוד פרנקפורטר שמיר, ג''וש שגיא, כרמל סלע, ניר שטראוס (קול), בר מרדיקס (תופים), אוהד לוי (פסנתר), שאולי פריד (גיטרת סולו ואקוסטית), יואב רוטברד (גיטרת רית''אם) ויגאל מרקוס (בס). אורי פניכל (מיקס מאסטרינג)., יובל גרבר') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description, "cast") VALUES ('המאהבת', 'המאהבת', 'הפקות עצמאיות', 75, 'קומדיה בלשית שחורה על ארבע נשים שמנסות לגלות את סוד עזיבת השכן, עם תפניות מפתיעות ותשוקות נסתרות.', 'קומדיה שחורה בניחוח בלשי, בה ארבע נשים נפגשות כדי לפתור את תעלומת עזיבת השכן מהקומה העליונה, תוך גילוי סודות ותשוקות נסתרות.', 'עירית בנדק, מיכל שטמלר, יעל איתן, שירי לוטן, אושר זיזמסקי') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description, "cast") VALUES ('יצרים רעים', 'יצרים-רעים', 'הפקות עצמאיות', 95, 'קומדיה שחורה על חיים כפולים, דחפים אפלים ומאבק פנימי על זהות, עם מסע מטורף של אהבה ואלימות.', 'קומדיה שחורה על הגבול בין שפיות לטירוף, בה לילי חיה חיים כפולים כמורה ומלכת סאדו-מאזו, ומגלה את הדחפים האפלים של עברה.', 'גיא באומהקר, נוי בן ברית, יהל פפו, טליה סגל, זוהר בדש, אליס דור-כהן, דניאל (דובי) דובילנסקי') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description, "cast") VALUES ('לאורה ריבלין - בעיר זרה', 'לאורה-ריבלין-בעיר-זרה', 'הפקות עצמאיות', 75, 'ערב מוסיקלי אישי של לאורה ריבלין, המשלב שירים מקוריים ומונולוגים נוקבים על החיים והמלחמה, עם נגיעות חדשניות ללהיטים מוכרים.', 'ערב מוסיקלי אישי עם שירים מקוריים ומונולוגים נוקבים על החיים, המצב והמלחמה, עם גרסאות כיסוי מפתיעות ללהיטים ישראליים.', 'ליאורה ריבלין') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description, "cast") VALUES ('להיות שם', 'להיות-שם', 'הפקות עצמאיות', 90, 'סאטירה תיאטרלית על שאנס, גנן שנזרק לעולם האמיתי ומגלה את כוחו הייחודי לשדר תקווה בעידן של משבר.', '''להיות שם'' מספר את סיפורו של שאנס, אדם שמטפס במקרה במעלה הסולם החברתי למרות שלא יצא מביתו כל חייו. כששאנס מגורש מביתו ונזרק לראשונה אל ''העולם האמיתי'', אנשים מוקסמים מתדמיתו הייצוגית ודימוייו היצירתיים השאולים מעולם הגננות. תחת חסות משבר כלכלי, שאנס זוכה באהדת הציבור המיואש בזכות תגובותיו הפשוטות והישרות, ומספק, ללא ידיעתו, מעט תקווה לחיים טובים יותר.', 'יז''י קושינסקי, נדב בלומנברג, עידו לפידוס, דריה פורר, איתי פורת') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description, "cast") VALUES ('מזוייפת', 'מזוייפת', 'הפקות עצמאיות', 90, 'דרמה קומית נועזת על מאבקיה של שחקנית בתיאטרון המודרני, המגלה שההצלחה דורשת יותר מכישרון בלבד.', 'דרמה קומית נועזת על אחורי הקלעים של עולם התיאטרון, שבה שירה, שחקנית מחוננת, מגלה שכישרון לבדו אינו מספיק. היא יוצאת למסע בין מסדרונות התיאטרון האפלים, שם כל דיאלוג הוא מניפולציה וכל מחווה מסתירה מזימה. ההצגה עוסקת במאבק בין אמנות אותנטית לבין הצורך בהכרה ותהילה.', 'שירי לוטן, הראל מוראד, שי אגוזי, מאיה בכובסקי') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description, "cast") VALUES ('מיכאל בן דוד- מופע פסנתר אינטימי', 'מיכאל-בן-דוד-מופע-פסנתר-אינטימי', 'הפקות עצמאיות', 75, 'מופע פסנתר אינטימי של מיכאל בן דוד, המשלב רגעים מחייו עם שירים מרגשים והומור.', 'מיכאל בן דוד במופע פסנתר חדש ואינטימי הפותח חלון אל מאחורי הקלעים של חייו. המופע כולל שירים ורגעים בלתי נשכחים מהילדות ועד להצלחותיו הבינלאומיות, ערב חשוף מצחיק מרגש ומלא כוח בו הקהל הוא חלק מהמסע.', 'מיכאל בן דוד') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description, "cast") VALUES ('רוורס', 'רוורס', 'הפקות עצמאיות', 70, 'דרמה פסיכולוגית עוצמתית על אסירה המנהיגה מרד, מתמודדת עם סודות מהעבר ומחפשת חופש אמיתי.', 'דרמה פסיכולוגית חדה על מחיר מול חופש, שבה אדווה, סופרת שהפכה לאסירה, מנהיגה מרד אסירות ומסרבת להסביר למה. היא נקרעת בין ניסיון לכפר על מה שעשתה לבין הפחד לגלות מי היא באמת. המחזה עוסק במחיר האהבה, חובת הלב והרצון בחופש.', 'יובל גרבר, עינת סגל כהן, מאי שטיימן, דיויד לוינסקי, ליעוז לוי, דמיאן פאור') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description, "cast") VALUES ('שלופתא', 'שלופתא', 'הפקות עצמאיות', 75, 'מופע אימפרוביזציה קומי שיביא לכם ערב של צחוק בלתי נגמר, עם מערכונים שמאולתרים במקום.', 'שלופתא הוא הרכב האימפרוביזציה המוביל בארץ, המציע מופע קומי שבו חמישה שחקנים, קלידן ותאורן מאלתרים יחד את הלא נודע. המופע כולל מערכונים קומיים שמאולתרים על המקום בהשראת רעיונות מהקהל, ויוצר אווירה של יצירה משותפת שמביאה לצחוק בלתי נגמר.', 'אור ורנר, איתי הכהן, יונתן גרובר, ירון ניצן, עידן לוי, אלעד ישי') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description, "cast") VALUES ('Next Stop', 'Next-Stop', 'הפקות עצמאיות', 60, 'קומדיה על סטארטאפיסט ושחקנית ישראלית בניו יורק, המנסים להגשים חלומות בעולם תאגידים ובידור.', 'קומדיה של טעויות בעולם היזמות, שבה סטארטאפיסט ישראלי מגיע לניו יורק להגשים את רעיונותיו העסקיים ופוגש שחקנית ישראלית-אמריקאית שמנסה להגשים את חלומה על במות ברודוויי. הם מנסים לממש את חלומותיהם בעיר ובתרבות שהם חושבים שהם מכירים.', 'בן פרי, יוני בלוך, בן פרי, נגה מילשטיין / מרני וולף, Noga Milstein, Mili Avital, Ben Perry, Mili Avital, Omri Anghel and Anne Streichman, Barak Feldman, Yoni Bloch, Adi Orni, Ira Faktor, Damian Marin') ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Show" (title, slug, theatre, "durationMinutes", summary, description, "cast") VALUES ('RePlay', 'RePlay', 'הפקות עצמאיות', 60, 'RePlay הוא מחזה מרגש על פרידה, זיכרונות ואופן ההתמודדות עם האהבה שהייתה, המשלב תיאטרון ומוזיקה חיה.', 'נדב ונגה, זוג שהתפרק, עומדים על במה ומנסים להבין את סיבות הפרידה. הם מפרקים את הזיכרונות והרגשות שנותרו, כשהשאלה האמיתית היא איך לחיות עם מה שנשאר.', 'אורן ברזילי, גאיה ענבר, בן איזדי') ON CONFLICT (slug) DO NOTHING;

-- ============================================================
-- 3. Insert ShowGenre join records
-- ============================================================
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'איב' AND g.name = 'מוזיקלי' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'איב' AND g.name = 'קומדיה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'דיברת-אלי' AND g.name = 'דרמה קומית' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'הולכים-לעולמם' AND g.name = 'קומדיה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'הלהצ-ר' AND g.name = 'מחזמר' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'הלהצ-ר' AND g.name = 'קומדיה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'המאהבת' AND g.name = 'קומדיה שחורה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'יצרים-רעים' AND g.name = 'קומדיה שחורה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'לאורה-ריבלין-בעיר-זרה' AND g.name = 'מוזיקלי' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'להיות-שם' AND g.name = 'סאטירה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'מזוייפת' AND g.name = 'דרמה קומית' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'מיכאל-בן-דוד-מופע-פסנתר-אינטימי' AND g.name = 'מוזיקלי' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'מיכאל-בן-דוד-מופע-פסנתר-אינטימי' AND g.name = 'מרגש' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'רוורס' AND g.name = 'דרמה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'שלופתא' AND g.name = 'קומדיה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'Next-Stop' AND g.name = 'קומדיה' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'RePlay' AND g.name = 'מרגש' ON CONFLICT DO NOTHING;
INSERT INTO "ShowGenre" ("showId", "genreId") SELECT s.id, g.id FROM "Show" s, "Genre" g WHERE s.slug = 'RePlay' AND g.name = 'דרמה' ON CONFLICT DO NOTHING;

-- ============================================================
-- 4. Reset sequences
-- ============================================================
SELECT setval(pg_get_serial_sequence('"Show"', 'id'), (SELECT MAX(id) FROM "Show"));
SELECT setval(pg_get_serial_sequence('"Genre"', 'id'), (SELECT MAX(id) FROM "Genre"));
